### ISSUE TITLE
Renaming to plugin.video.vrtmax will cause issues

### ISSUE THREAD

**Issue by dagwieers** [add-ons/plugin.video.vrt.nu#1011]
### Describe the bug ###

As discussed on Slack, renaming the addon id will cause problems with the upgrade path, as we can not push updates with a new addon id to older repos, and the add-on may not automatically upgrade.

**Comment by mediaminister** [comment]
Fixed in https://github.com/add-ons/plugin.video.vrt.nu/pull/1012
