### ISSUE TITLE
New VRT MAX not working.

### ISSUE THREAD

**Issue by ldebt** [add-ons/plugin.video.vrt.nu#1023]
All methods to start a program are failing and result in the message "VRT MAX fout   Controleer log voor meer informatie"

**Comment by mediaminister** [comment]
Please test the new release: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.15

**Comment by ldebt** [comment]
New version v2.5.15 installed from zip file on usb stick. Problem is solved. Thank you.
