### ISSUE TITLE
What's the new URL for het journaal?

### ISSUE THREAD

**Issue by TASSDevon** [add-ons/plugin.video.vrt.nu#1028]
```
item:
  file: plugin://plugin.video.vrt.nu/play/latest/het-journaal
method: Player.Open
```

used to work but now it complains that the json file is empty. I saw VRT changed the name of Het Journaal but what exactly should it be in this url?

**Comment by mediaminister** [comment]
The new name is `vrt-nws-journaal`, you can look this up using the program A-Z listing on https://www.vrt.be/vrtnu/a-z/
So the add-on url is:
```
plugin://plugin.video.vrt.nu/play/latest/vrt-nws-journaal
```
