### ISSUE TITLE
Live streams not playing in NL

### ISSUE THREAD

**Issue by jcjdammers** [add-ons/plugin.video.vrt.nu#1040]
### Describe the bug ###
When I select a live channel for watching then I am getting the popup error window saying **"Dit programma kan enkel afgespeeld worden vanuit een lidstaat van de Europeese Unie. Het wordt geblokkeerd op jouw geografische lokatie op basis van je IP-adres. Meer info op ......"**
However it always worked before, and I can still watch all the live channels on my other (non-Kodi) devices (e.g. vrt-max app on iPhone and iPad, or webbrowser on PC).

### To Reproduce ###
1. Select a live channel for watching, for example "Eén live" or "Canvas live"

### Expected behavior ###

The stream should play (as it always did before :-)

### Additional context ###

- Operating system: LibreELEC 10.0.2
- Kodi version: 19.4
- Addon version: 2.5.16+matrix.1
- Using a VPN: no
- Country you are using the addon from: NL 

### Log (if available) ###
```paste below
https://paste.kodi.tv/vujahacupu




```
![unnamed](https://user-images.githubusercontent.com/10573570/189958852-61bdcdd9-7a82-4d5b-87a3-618a6255c64b.jpg)

**Comment by mediaminister** [comment]
Thanks for reporting this bug.
I made a fix.
Please test:
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.16+matrix.1-roaming-cc2b419.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9562976/plugin.video.vrt.nu-2.5.16%2Bmatrix.1-roaming-cc2b419.zip)
Kodi 18 Leia:[plugin.video.vrt.nu-2.5.16-roaming-cc2b419.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9562977/plugin.video.vrt.nu-2.5.16-roaming-cc2b419.zip)

**Comment by jcjdammers** [comment]
The fix works, thanks a lot !!

**Comment by mediaminister** [comment]
Thanks for confirming.
