### ISSUE TITLE
fatal error: 404

### ISSUE THREAD

**Issue by K-Ray** [add-ons/plugin.video.vrt.nu#1051]
https://search7.vrt.be/ gives a 404 error and I can't find or play any video anymore since today.
anything I can patch?

- Operating system: linux
- Kodi version: 19.1
- Addon version: 2.5.17
- Using a VPN: no
- Country you are using the addon from: BE

### Log (if available) ###
2022-10-05 19:52:31.057 T:4353    FATAL <general>: [plugin.video.vrt.nu] HTTP Error 404: Not Found
2022-10-05 19:52:31.535 T:4353    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/home/kvr/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/home/kvr/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 335, in run
                                                       plugin.run(argv)
                                                     File "/home/kvr/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/kvr/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/kvr/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 146, in programs
                                                       VRTPlayer().show_episodes_menu(program_name=program_name, season=season)
                                                     File "/home/kvr/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 271, in show_episodes_menu
                                                       episode_items, sort, ascending, content = self._apihelper.list_episodes(program_name=program_name, season=season)
                                                     File "/home/kvr/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 135, in list_episodes
                                                       episodes = self.get_episodes(program=program_name, season=season, category=category, feature=feature, programtype=programtype, page=page,
                                                     File "/home/kvr/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 643, in get_episodes
                                                       api_pages = search_json.get('meta').get('pages').get('total')
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--

**Comment by mediaminister** [comment]
VRT removed the search API.
This means most menus stopped working.
I'm working on a fix. Work in progress!
I have already fixed the 'Most recent' and favorite programs menu.
The TV guide menu and Live TV menu should work.
You can test this:
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.17+matrix.1-menufix-6bad201.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9717971/plugin.video.vrt.nu-2.5.17%2Bmatrix.1-menufix-6bad201.zip)
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.17-menufix-6bad201.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9717972/plugin.video.vrt.nu-2.5.17-menufix-6bad201.zip)

**Comment by blowk** [comment]
Thanks for the quick fix.
Just tested it out and TV guide is working.

**Comment by K-Ray** [comment]
Thanks for the fix! 
Just what I needed :)

**Comment by mediaminister** [comment]
I fixed the categories menu.
Test packages:
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.17+matrix.1-menufix-a774819.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9718764/plugin.video.vrt.nu-2.5.17%2Bmatrix.1-menufix-a774819.zip)
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.17-menufix-a774819.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9718765/plugin.video.vrt.nu-2.5.17-menufix-a774819.zip)

**Comment by david63236** [comment]
tried to watch "Hotel Romantiek: de kijk van de kroost",
but same problem occurs for "Uitgelicht aanbod - Exclusief online"


Same problem exits for "Kanalen" and "Uitgelicht aanbod",
error xxx for "Entertainment", Human Interest" and "Wetenschap & Natuur" categories

**Comment by mediaminister** [comment]
Is "Hotel Romantiek: de kijk van de kroost" in one of the featured lists on the homepage?

I already fixed the featured menu.
Test packages:
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.17+matrix.1-featured-d0e32f3.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9726227/plugin.video.vrt.nu-2.5.17%2Bmatrix.1-featured-d0e32f3.zip)
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.17-featured-d0e32f3.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9726226/plugin.video.vrt.nu-2.5.17-featured-d0e32f3.zip)

**Comment by david63236** [comment]
On VRT Max website homepage, it appears in "Nieuw toegevoegd" and 
the resulting URL is https://www.vrt.be/vrtnu/a-z/hotel-romantiek--de-kijk-van-de-kroost/
and has the "Human Interest" label,
it is also available from the "Alle programma's" link on the homepage

So I tested d0e32f3 and checked the Human Interest categorie,
but this categorie gives an error : 
    Error Type: <class 'AttributeError'>
    Error Contents: 'NoneType' object has no attribute 'get'
    ...\Kodi 19-3 Matrix\portable_data\addons\plugin.video.vrt.nu\resources\lib\addon_entry.py", line 14, in <module>
After that i checked the "Alle programma's" item of d0e32f3,
but this isn't working, it keeps searching, so I stopped it after 5 minutes

**Comment by mediaminister** [comment]
Yes, "Alle programma's" and "Zoeken is still broken.

**Comment by ghen2** [comment]
Latest test packages are working for me, thanks @mediaminister!

**Comment by mediaminister** [comment]
More fixes, search menu is working.
Test packages:
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.17+matrix.1-search-83ec233.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9727724/plugin.video.vrt.nu-2.5.17%2Bmatrix.1-search-83ec233.zip)
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.17-search-83ec233.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9727725/plugin.video.vrt.nu-2.5.17-search-83ec233.zip)

**Comment by bart-fs1** [comment]
hier ook :-)

**Comment by mediaminister** [comment]
"All programs" menu is still broken, I didn't find an API method yet to get the program list. You can use "Categories" menu instead of the "Search" menu.
I fixed "Soon offline" menu.
Test packages:
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.17+matrix.1-offline-9ff172f.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9731117/plugin.video.vrt.nu-2.5.17%2Bmatrix.1-offline-9ff172f.zip)
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.17-offline-9ff172f.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9731118/plugin.video.vrt.nu-2.5.17-offline-9ff172f.zip)

**Comment by david63236** [comment]
9ff172f tested: I confirm that "Binnenkort offline", "Zoeken" and "Categorieen" (all categories) are working.

Concerning "All programs", maybe it is possible with
- a search for everything (search is already working)
- a fetch of all categories (categories is already working)

**Comment by mediaminister** [comment]
No solution for the "All programs" menu yet.
Other menus are fixed in the new v2.5.18 release: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.18
I'll close this, please open a new issue when you encounter an error with version v2.5.18
