### ISSUE TITLE
error when wanting to browse to all programs

### ISSUE THREAD

**Issue by bart-fs1** [add-ons/plugin.video.vrt.nu#1056]
Describe the bug
To Reproduce

Go to add ons, vrt nu, catgeories, children and youth
Click on ....
Scroll down to ....
See error
Expected behavior
list of all programs in this category like it was before

Additional context
Operating system: win11 but also on smart tv android ...
Kodi version: 19.4
Addon version: 2.5.17+matrix.1
Using a VPN: no
Country you are using the addon from: belgium

**Comment by mediaminister** [comment]
Please see https://github.com/add-ons/plugin.video.vrt.nu/issues/1051
