### ISSUE TITLE
Plugin not using correct URL for episode

### ISSUE THREAD

**Issue by TASSDevon** [add-ons/plugin.video.vrt.nu#1071]
It looks like VRT changed the URLs again? The following is not working anymore when calling with Kodi RPC:

`file: plugin://plugin.video.vrt.nu/play/latest/vrt-nws-journaal`

Getting a HTTP Error 404, the strange thing is, in the url the query parameter is set to journaal instead of vrt-nws-journaal, any ideas?

**Comment by mediaminister** [comment]
VRT removed the search API endpoint. That is the reason you get a 404.
I need to migrate the 'latest episode' function to the new GraphQL API.
I can take a look at it next week.

**Comment by TASSDevon** [comment]
Thanks, looking forward to it!

**Comment by mediaminister** [comment]
Please test:
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.19-latest-16b6614.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9951929/plugin.video.vrt.nu-2.5.19-latest-16b6614.zip)
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.19+matrix.1-latest-16b6614.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/9951930/plugin.video.vrt.nu-2.5.19%2Bmatrix.1-latest-16b6614.zip)

**Comment by TASSDevon** [comment]
Tried with the Kodi 19 version and it seems to work!

**Comment by mediaminister** [comment]
Thanks for confirming.
