### ISSUE TITLE
Kodi 20 subtitles scroll up in live view

### ISSUE THREAD

**Issue by alfaajx732** [add-ons/plugin.video.vrt.nu#1093]
This problem occurs only in live view and since Kodi 20 and VRT MAX add-ons

### To Reproduce ###
Kodi 20.0 for Windows 11
add-ons VRTMAX
Live kijken
Een live | Thuis

Kodi 20 for Android no subtitles 

### Additional context ###

- Operating system: Windows 11
- Kodi version: 20.0
- Addon version: 2.5.20
- Using a VPN: no
- Country you are using the addon from: Belgium

![327539530_926889822090022_8717748373549706835_n](https://user-images.githubusercontent.com/76863831/214921936-d7148297-9d6d-4660-ace9-734ca21732e5.jpg)

**Comment by mediaminister** [comment]
It's a Kodi 20 problem, fixed in https://github.com/xbmc/xbmc/pull/22567

**Comment by peno64** [comment]
Fixed in kodi 20.1
