### ISSUE TITLE
VRT Max streaming problems after updating to Matrix 19.5/Libreelec 10.0.4

### ISSUE THREAD

**Issue by Clyde72** [add-ons/plugin.video.vrt.nu#1094]
I never had problems with streaming from VRT Max. 

I'm using Kodi on rpi 3 B+ running Matrix.

Recently I got an alert that there was an update for Libreelec. So I've updated to 10.0.4 and now I'm having serious streaming problems with VRT Max. Nothing is in sync. Video stream lags, stutters, is behind on audio. Also subs are not in sync. Video even freezes at times. Horrible to watch. Seems like audio is on track though. Also starting streams in general takes longer than before the update. 

First noticed it when watching "Het verhaal van Vlaanderen". With foreign series like "Bloodlands" it is really bad.

I've tried changing Widevine version but doesn't do a thing.

Goplay & VTM Go streams work as usual so it must have to do with VRT Max add on.

**Comment by Clyde72** [comment]
> I never had problems with streaming from VRT Max.
> 
> I'm using Kodi on rpi 3 B+ running Matrix.
> 
> Recently I got an alert that there was an update for Libreelec. So I've updated to 10.0.4 and now I'm having serious streaming problems with VRT Max. Nothing is in sync. Video stream lags, stutters, is behind on audio. Also subs are not in sync. Video even freezes at times. Horrible to watch. Seems like audio is on track though. Also starting streams in general takes longer than before the update.
> 
> First noticed it when watching "Het verhaal van Vlaanderen". With foreign series like "Bloodlands" it is really bad.
> 
> I've tried changing Widevine version but doesn't do a thing.
> 
> Goplay & VTM Go streams work as usual so it must have to do with VRT Max add on.

Changing Max resolution for Inputstream Adaptive to 720p seems to have solved it

**Comment by mediaminister** [comment]
This problem has nothing to do with the VRT MAX Add-on, the add-on just gets the stream url and loads this in Kodi Player.

VRT MAX normally provides 1080p50 resolution and therefore your system needs enough computing power/hardware acceleration to process video with 50 high resolution frames a second. I guess the new Libreelec version broke the hardware acceleration.
VTM Go and Goplay provides 720p25 or 1080p25, this resolution only contain 25 frames a second which needs less processing power.
