### ISSUE TITLE
Audio not in sync on VRT Max

### ISSUE THREAD

**Issue by PeterCloet** [add-ons/plugin.video.vrt.nu#1140]
### Describe the bug ###
My Kodi (RPI4 Model B, 2Gb, LibreElec 10.0.2) is connected to a new television set (Samsung QE55S95B - Model 2022). Video and audio are set to go through HDMI [3840x2160 & Alsa Default (vc4-hdmi-0 MAI PCM i2s-hifi-0)]. I'm using an official RPi4 HDMI cable which is certified for 4K traffic streams.
All content, including streams from VTMGo & GoPlay, plays fine with the audio in sync. However, the **VRTMax** add-on, **doesn't keep the audio in sync**. It starts in sync and then "drifts off" quite rapidly after a second or two. This is the case for all streams on VRT Max I tried.
When I reconnect the Kodi box to the previous television set (Samsung HDTV UE42F5700), the issue disappears and the audio remains fine. FYI. No (audio) settings were changed during this process.

### To Reproduce ###
Play VRT Max stream on Samsung QE55S95B)

### Expected behavior ###
I'm not really sure what is causing the issue here. As the VRT Max add-on is playing fine on the previous television, I suspect it has something to do with the new one, possibly the HDMI characteristics.

### Additional context ###

- Operating system: LibreElec 10.0.2 running on RPi4
- Kodi version: 19.4
- Addon version: 2.5.26 + Matrix.1
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
None

**Comment by mediaminister** [comment]
This problem has nothing to do with the VRT MAX Add-on, the add-on just gets the stream url and loads this in Kodi Player.

VRT MAX normally provides 1080p50 resolution, this video resolution contains 50 frames a second and therefore your Kodi system and hardware needs to support this.
VTM GO and GoPlay provide 720p25 or 1080p25, this video resolution only contains 25 frames a second.

So, the 50 fps is the only difference between VRT MAX and VTM GO/GoPlay.

**Comment by PeterCloet** [comment]
Hi,
Ok. I understand the underlying issue now.
The refresh rate of my Kodi RPi on 3840x2160 has a maximum of 30. If I bring the resolution down to 1920x1080, I can set a higher refresh rate (50, 60, 100). When running at this higher rate, the audio is back in sync. Solved.
Thanks for pointing out the difference in video resolutions and frame rates to me.
