### ISSUE TITLE
Most Categories are empty

### ISSUE THREAD

**Issue by lebeno** [add-ons/plugin.video.vrt.nu#1151]
### Describe the bug ###
Going to VRT MAX > Categoriën > Cultuur: the list is empty
Same for Audiodescriptie, Entertainment, Human Interest, Humor, Kinderen en Jongeren, Koken...
Other categories do list programmes: Docu, Film, Series, Talkshows...

I have tried rebooting Kodi. No change.
I have upgraded to LibreELEC 11.0.6, no change

"Live kijken" works, "Meest Recent" also works.

### Additional context ###
- Operating system: Libreelec 11.0.6
- Kodi version: 20.3.0
- Addon version: 2.5.28+matrix.1
- Using a VPN: no
- Country you are using the addon from: BE

**Comment by mediaminister** [comment]
VRT MAX changed their API, so this suddenly stopped working.

I made a fix, please test:
Kodi 18: [plugin.video.vrt.nu-2.5.28-categories-5935df1.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/14239105/plugin.video.vrt.nu-2.5.28-categories-5935df1.zip)
Kodi 19/20/21: [plugin.video.vrt.nu-2.5.28+matrix.1-categories-5935df1.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/14239106/plugin.video.vrt.nu-2.5.28%2Bmatrix.1-categories-5935df1.zip)

**Comment by lebeno** [comment]
That seems to fix the problem. Thank you!

**Comment by mediaminister** [comment]
Thanks for confirming.
Fixed and released: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.29
