### ISSUE TITLE
In Categories only 100 items are returned

### ISSUE THREAD

**Issue by ErwinBaeyens** [add-ons/plugin.video.vrt.nu#1159]
### Describe the bug ###
When selecting Categories and Series, only 100 items are returned.  The list stops today at Red Rock.  I.e Series like "Thuis", "Undercover" or "Vera" cannot be seen in the list. These can be found when searching for them.   I have experimeted with the length of the "Number of items per page" property in the settings and when set to 50  I get 2 pages and the list stops at "Red Rock"  when setting it to 300 or 200 I get one page that stops after 100 items. 

### To Reproduce ###
1. Go to Categories/Series
2. Scroll down to the last item of the last page and there are a lot of items missing that come later in the list.
4. There is no error message but the list is always truncated at max 100 items.

### Expected behavior ###

When a  category contains more than 100 Titles these should be shown 

### Additional context ###

- Operating system: LibreELEC 10.0.04 on Raspberry PI 4
- Kodi version: 19.5.0
- Addon version: 2.5.29+matrix 1
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
No relevant info in the log files as there is no real error message.

**Comment by mediaminister** [comment]
At first sight this problem also occurs on VRT MAX Website: https://www.vrt.be/vrtmax/zoeken/?facets=%5B%7B%22name%22%3A%22contenttype%22%2C%22values%22%3A%5B%22series%22%5D%7D%2C%7B%22name%22%3A%22entitytype%22%2C%22values%22%3A%5B%22video-program%22%5D%7D%5D

**Comment by ErwinBaeyens** [comment]
Can this be reported at VRT somewhere?  It might not be unthinkable  that they don't know this bug exists

**Comment by mediaminister** [comment]
Yes, you can report this to VRT: https://www.vrt.be/heb-je-een-vraag/s/contactsupport-vrtnu

**Comment by mediaminister** [comment]
Fixed and released: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.32
