### ISSUE TITLE
Categories are empty

### ISSUE THREAD

**Issue by blowk** [add-ons/plugin.video.vrt.nu#1165]
### Describe the bug ###
Going to VRT MAX > Categoriën
All options like Cultuur, Audiodescriptie, Entertainment, Human Interest, Humor, Kinderen en Jongeren, Koken...
are empty.

"Live kijken", "Meest Recent", "Mijn favorieten" also works.

### Additional context ###
Operating system: Android
Kodi version: 21.0
Addon version: 2.5.29+matrix.1
Using a VPN: no
Country you are using the addon from: BE

**Comment by mediaminister** [comment]
VRT changed their API.
I made a fix, please test:
Kodi 19, 20, 21: [plugin.video.vrt.nu-2.5.30+matrix.1-api-29abe4c.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/15016628/plugin.video.vrt.nu-2.5.30%2Bmatrix.1-api-29abe4c.zip)
Kodi 18: [plugin.video.vrt.nu-2.5.30-api-29abe4c.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/15016627/plugin.video.vrt.nu-2.5.30-api-29abe4c.zip)

**Comment by blowk** [comment]
Yes, it's working again.
Thank you very much for the fix.

**Comment by snapet** [comment]
Can confirm.
You rule!

Thanks a lot!

**Comment by mediaminister** [comment]
This is released now: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.31

**Comment by thomasddn** [comment]
Just wondering: is this going to be released through the official add-on repository or is it only available as manual install? Currently I still see v2.5.29 on my installation (OSMC with Kodi v20.5).

**Comment by blowk** [comment]
I see that the categories are empty.
VRT changed the endpoints again.

**Comment by blowk** [comment]
> Just wondering: is this going to be released through the official add-on repository or is it only available as manual install? Currently I still see v2.5.29 on my installation (OSMC with Kodi v20.5).

You could download the zip file and manually install if it doesn't comes up in the official add-on repository.

**Comment by mediaminister** [comment]
> Just wondering: is this going to be released through the official add-on repository or is it only available as manual install? Currently I still see v2.5.29 on my installation (OSMC with Kodi v20.5).

This is submitted and merged 2 weeks ago in de official Kodi repo.
Maybe you should manually install the update if automatic updates are disabled.

**Comment by thomasddn** [comment]
> This is submitted and merged 2 weeks ago in de official Kodi repo. Maybe you should manually install the update if automatic updates are disabled.

Updates should install automatically, but I'll double check later today. This page also still displays v2.5.29: https://kodi.tv/addons/omega/plugin.video.vrt.nu/.

**Comment by mediaminister** [comment]
2.5.31 is in the repo: https://mirrors.kodi.tv/addons/nexus/plugin.video.vrt.nu/
