### ISSUE TITLE
VRTMAX Search function doesn't work, Nothing found is returned.

### ISSUE THREAD

**Issue by alfaajx732** [add-ons/plugin.video.vrt.nu#1174]
VRTMAX Search function doesn't work (anymore), nothing found is returned.

### Describe the bug ###
When i start a new search in vrtmax it returns always "Nothing was found" 
### To Reproduce ###
1. Go to vrtmax
2. Click on new search item
3. Nothing found is the answer

### Expected behavior ###
returns list of found items 

### Additional context ###
- Operating system: Windows 11 and Android
- Kodi version: 21
- Addon version: 2.5.31
- Using a VPN: no
- Country you are using the addon from: Belgium

**Comment by mediaminister** [comment]
Should be fixed in the master branch, please test this package: [plugin.video.vrt.nu-2.5.31+matrix.1-master-c1ce744.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/15358472/plugin.video.vrt.nu-2.5.31%2Bmatrix.1-master-c1ce744.zip)

**Comment by mediaminister** [comment]
Fixed and released: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.32

**Comment by peno64** [comment]
@mediaminister 
It looks like that the Leia version is not updated to 2.5.32
It is still 2.5.31

**Comment by mediaminister** [comment]
I know, official Kodi repository doesn't accept Python 2.7 add-ons anymore: https://kodi.tv/article/the-sun-sets-on-python-2/
You can download and manually install the new version in Kodi Leia: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.32
Or you can upgrade to a more recent Kodi version.
