### ISSUE TITLE
Shaking video in some streams

### ISSUE THREAD

**Issue by keiem** [add-ons/plugin.video.vrt.nu#1180]
### Describe the bug ###
In "De goudvis" and "Kalm Waes" the video starts shaking after several minutes of play.  When I turn on the OSD menu the shaking stops.

### To Reproduce ###
Just start the stream of "De Goudvis" or "Kalm Waes" and watch some minutes.

### Additional context ###
- Operating system: Libreelec 12.0.1
- Kodi version: 21.1
- Addon version:Latest
- Using a VPN: no
- Country you are using the addon from: Belgium

On my x86-64 arch linux pc, the stream freezes after some seconds.  It's possible my pc isn't fit to play those streams.  It's a old pc, probably without video (h264) acceleration.

### Log (if available) ###
Which log should I collect?

**Comment by mediaminister** [comment]
This is not a VRT MAX add-on problem. Video content is provided by VRT in 1080p50 format, so your hardware needs to support 50 frames per second.

To play VRT MAX content on older devices you can lower video quality settings in the InputStream Adaptive add-on to 720p or lower.

**Comment by keiem** [comment]
@mediaminister 

Thanks fpor the response.  I already tried to lower the video quality but it didn't seem to work, maybe I did it the wrong way.  
When I download the episodes first, I can watch them without problems on the same hardware.  Maybe there is something wrong with libreelec as I started having problems with several add-ons since I upgraded to LE12.

**Comment by keiem** [comment]
@mediaminister 

seems something went wrong during my last update of libreelec.  I reinstalled everything and now it works as expected.
