### ISSUE TITLE
Wrong date format in VRT MAX Tv-guide

### ISSUE THREAD

**Issue by CoderPupil** [add-ons/plugin.video.vrt.nu#1188]
### Describe the bug ###
The day-number is not showing, there is **-d** where the day number should appear.
Maandag **-d** oktober 2024

### To Reproduce ###
1. Go to Tv-gids
2. See wrong date format

### Expected behavior ###
Seeing the right date format
Maandag 14 oktober 2024

### Additional context ###

- Operating system: Android TV 14.0.0 API level 34 (Google TV Streamer 4K)
- Kodi version: 21.1.0 with standard Estuary skin
- Addon version: 2.5.32+matrix.1
- Using a VPN: no
- Country you are using the addon from: Belgium

I don't know if this is a VRT MAX, Kodi or skin issue

[https://photos.app.goo.gl/3WsM2aSiGKrUiDNs9](https://photos.app.goo.gl/3WsM2aSiGKrUiDNs9)

**Comment by mediaminister** [comment]
This is a Kodi issue on Android since Kodi 21: https://github.com/xbmc/xbmc/issues/25066

But since team Kodi isn't fixing this for months, I'll look into this and I'll fix it with a workaround in the VRT MAX add-on.

**Comment by mediaminister** [comment]
I fixed it, please report if the following test package works: [plugin.video.vrt.nu-2.5.32+matrix.1-datelong-190fd60.zip](https://github.com/user-attachments/files/17209312/plugin.video.vrt.nu-2.5.32%2Bmatrix.1-datelong-190fd60.zip)

**Comment by CoderPupil** [comment]
Great, it works. Thanks for fixing it!

**Comment by mediaminister** [comment]
Fixed in https://github.com/add-ons/plugin.video.vrt.nu/pull/1189
