### ISSUE TITLE
search fails & categories empty since 2024/11/26

### ISSUE THREAD

**Issue by davidbe** [add-ons/plugin.video.vrt.nu#1197]
### Describe the bug ###
The contents of all the categories are empty.
Searching fails as well.

API change probably...

### To Reproduce ###
Steps to reproduce the behaviour:
1. Go to Categories > Films (or any other category
2. Empty list!

1. Go to Search > "thuis"
2. Error: Nothing was found when searching for: thuis

### Expected behavior ###
Non empty lists & search result

### Additional context ###
- Operating system: Linux on Vero V
- Kodi version: 21.1
- Addon version: 2.5.32
- Using a VPN: no
- Country you are using the addon from: Belgium

**Comment by erik-pe** [comment]
Same problem here.
Description of problem is exactely the same as Davidbe describes.
I can only add that in my case, the other items from the top menu (like "Most Recent", "Soon Offline" ... are working normally.
Only "Categories" shows no programs and search function does not work.
My situation:
Odroid N2Plus hardware
Coreelec 21.1.1 - Omega
Addon version: 2.5.32
No VPN
Watching from Belgium
Best regards

**Comment by davidbe** [comment]
@maintainers (@mediaminister ?), I'd like to improve my knowledge of this Kodi-add-on and like to know 'how' you investigate this issue. Maybe I can help with these (minor?) changes in the future?

**Comment by jekkos** [comment]
same issue here. Did someone gather any logs?

**Comment by mediaminister** [comment]
@davidbe A Kodi Add-on is just Python code, learn to program Python.

You should look at the API requests and JSON responses from VRT MAX app or website.
I fixed it, I had to lookup the new listId format VRT MAX is using now: https://github.com/add-ons/plugin.video.vrt.nu/pull/1198/files

Test package with this fix: [plugin.video.vrt.nu-2.5.32+matrix.1-api-4a60dc7.zip](https://github.com/user-attachments/files/17968055/plugin.video.vrt.nu-2.5.32%2Bmatrix.1-api-4a60dc7.zip)

**Comment by erik-pe** [comment]
@mediaminister 
Testpackage solves the issue for me!
Thanks a lot.

**Comment by mediaminister** [comment]
Thanks for confirming, this is released now in [2.5.33](https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.33)

**Comment by davidbe** [comment]
> @davidbe A Kodi Add-on is just Python code, learn to program Python.
> 
> You should look at the API requests and JSON responses from VRT MAX app or website. I fixed it, I had to lookup the new listId format VRT MAX is using now: https://github.com/add-ons/plugin.video.vrt.nu/pull/1198/files

Thank you for the quick solution!
I've some Python-knowledge, but just little experience with working with API. If API would change drastically, how do you discover those changes? This happened a few months ago with VTMGo and I learned that the maintainer uses the android-app in a virtual android on its machine to discover the requests and responses that goes out & in the app. It took a while to set up such an environment. 😅 
Is this similar to what is needed for VRTMax add-on?

Kind regards, david

**Comment by mediaminister** [comment]
The easiest way to study the VRT MAX api is to open the VRT MAX website and view the https requests in the network tab of your web browser's developer tools.

Using the VRT MAX Android app you need to intercept the https requests using Frida server and client, mitmproxy and a rooted Android system. A Android VM is one way, a rooted Android phone is another way.

**Comment by jekkos** [comment]
Installed the fix today, works great!
