### ISSUE TITLE
Live TV streams are not playing since update to v2.5.33

### ISSUE THREAD

**Issue by jcjdammers** [add-ons/plugin.video.vrt.nu#1200]
Hi,
After the update to v2.5.33 the Live TV streams are not playing anymore.
I am using LibreELEC 12.0.1 with Kodi (Omega) v21.1.
Can you please check?
Thanks, Jeroen.

```

**Comment by mediaminister** [comment]
I checked with LibreELEC 12.0.1 and livestreams are playing fine.
Please provide a full debug log so I can investigate: https://kodi.wiki/view/Log_file/Easy

**Comment by jcjdammers** [comment]
Here is my log-file:

https://paste.kodi.tv/sipojuhiyu

Thanks for your help.

**Comment by mediaminister** [comment]
I guess there is something wrong with the file system of your hardware. Try "Invalidate local http caches" in VRT MAX Addon expert settings.

If this doesn't work, you need to enable "debug logging" in the expert settings and provide a full debug log so I can investigate more.

**Comment by jcjdammers** [comment]
Hi,
Why do you think something is wrong with the file system? I experience no problems with my device and also with the previous version of the VRT MAX Addon the Live streams were working fine.
I did "Invalidate local http caches" but it didn't solve the problem.
VRT 1 live, VRT Canvas live, Ketnet live, Sporza live are not playing and show a popup window with an error message (see below).
Strange enough the "Ketnet Junior live" stream is playing fine.

I have enabled the debug logging in the VRT MAX Addon expert settings.
This is the new log:
https://paste.kodi.tv/hudobibepi


![vrt_max_error](https://github.com/user-attachments/assets/cb0d93fa-e823-4362-8bcc-11ce028f3ce7)

**Comment by mediaminister** [comment]
This is not yet a debug log, I forgot you need to enable debug logging also in Kodi system settings.

Live stream info is cached, so I thought maybe the cache wasn't written.

Ketnet Junior live uses another type of streaming server (Uplynk), so this works.

For some reason you don't get the streaming urls for the other channels and the error message is "None".
Maybe removing VRT Tokens in expert settings helps.

**Comment by jcjdammers** [comment]
Removing VRT Tokens didn't help either :-(
Here is another log with debugging enabled in Kodi system settings: 
https://paste.kodi.tv/susanugaze

**Comment by mediaminister** [comment]
Can you try this fix:
[plugin.video.vrt.nu-2.5.33-live-b05e21b.zip](https://github.com/user-attachments/files/18029167/plugin.video.vrt.nu-2.5.33-live-b05e21b.zip)

**Comment by jcjdammers** [comment]
It doesn't install. It says:
`2024-12-05 21:30:53.129 T:1926    error <general>: CAddonInstallJob[plugin.video.vrt.nu]: De afhankelijkheid op xbmc.python versie 2.25.0 kan niet worden voldaan.`

**Comment by jcjdammers** [comment]
I have installed the zip with the fix, and the Live TV streams are working again :-)
Many thanks.
