### ISSUE TITLE
Add TV livestreams to an IPTV PVR client

### ISSUE THREAD

**Issue by dagwieers** [add-ons/plugin.video.vrt.nu#209]
So the basic idea is that our users have their TV channels added to the TV section in their Kodi and can more easily switch between Live TV channels like they are used to on a normal TV.

To make this possible, various things should be considered:
- Either improve the existing IPTV Simple Client, or create a new IPTV PVR addon for this purpose
- The IPTV PVR addon needs an API to add/remove/query added streams
- Discuss with other stakeholders (other addon writers) for integration
- Either allow the user to do this on individual channels (right-click menu on channel) or do it automatically for all live channels
  - May cause duplicate entries if multiple overlapping addons, e.g. VRT NU vs Retrospect
- Optionally add EPG information when adding the channel
- Register the owner-addon of the channel
  - So that the user can right-click back to the addon for VOD content
- Automatically update entries when the VRT NU addon has changes (idempotent interface)

This solves the basic problem most users have that the TV channels are hidden inside addons, or need to be added to Favourites (where they are listed in between other stuff).

**Comment by dagwieers** [comment]
cc @michaelarnauts

**Comment by michaelarnauts** [comment]
This might be useful to look into: https://forum.kodi.tv/showthread.php?tid=301993

**Comment by dagwieers** [comment]
If anything, I think we need to discuss merits with other add-on and Kodi developers.
Maybe something better is already in the works.

**Comment by dagwieers** [comment]
I am going to close this for now. This is still high on my wishlist, but something I think Kodi should be fixing higher up.

With Video-on-demand becoming *the* future of media consumption, there should be Kodi infrastructure ready where add-ons can add content and live-streams, and which is easily accessible for users without the need to select a provider/add-on first.

**Comment by dagwieers** [comment]
This might be a solution to get VRT channels added to the TV channels listing in Kodi: https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html

**Comment by dagwieers** [comment]
A discussion is taking place in add-ons/plugin.video.vtm.go#168 wrt. this.

**Comment by dagwieers** [comment]
IPTV Manager has been accepted in the official Kodi repository, so this is now possible implemented and released.
