### ISSUE TITLE
Some on demand programs are not played until the end.

### ISSUE THREAD

**Issue by mediaminister** [add-ons/plugin.video.vrt.nu#281]
When VRT serves VOD-programs from a livestream([Live to VOD](https://www.google.com/search?q=%22live+to+vod%22)) with the so called "[virtual subclips](http://docs.unified-streaming.com/documentation/vod/player-urls.html#virtual-subclips)", the VRT NU add-on doesn't play the stream till the end of the program. 

This bug occurs mostly with live current affair programs like "Het Journaal", "Terzake", "De Afspraak", and "De Zevende Dag" while VRT broadcasts them.

You can bypass this bug by waiting to watch the program until VRT has broadcasted the program completely.

**Comment by dagwieers** [comment]
The experience I have had just now is that if an on-going live program is listed, it is often listed as a 02:00:00 (2-hour) video. This has 2 consequences I noticed:
- If you watch it 15 minutes after the start, it appears to stop after 15 minutes, if you then rewatch 45 minutes after the start, it stops after 45 minutes
- If the live stream overruns those 2 hours, it will stop at 2 hours and it may take some time before a longer running entry (in this case 02:25:05) appears with the full live stream

It is seldom a good idea to watch a live video delayed, if you watch only 15 minutes too late, you can start the live TV stream and rewind 15 minutes to watch the start without hiccups until the end.

**Comment by dagwieers** [comment]
Discussing this on Facebook I wonder how VRT NU's web player handles this. If this is reproducible, we can report this upstream. If other players handle this better, we can report this upstream as a point of improvement (inputstream.adaptive).

**Comment by mediaminister** [comment]
I'll check this in a couple of minutes: https://www.vrt.be/vrtnu/a-z/het-journaal/2020/het-journaal-het-journaal-13u-20200720/

**Comment by mediaminister** [comment]
VRT NU's web player dynamically updates the total time while playing a Live-to-VOD stream URL if only a start timestamp is provided: https://live-cf-vrt.akamaized.net/groupc/live/8edf3bdf-7db3-41c3-a318-72cb7f82de66/live.isml/.mpd?t=2020-07-20T11:07:00

But it seems Kodi (IA) always needs a stop timestamp **in the past** to start a Live-to-VOD stream at the start timestamp. In all other cases Kodi(IA) treats the stream as an ordinary livestream.

**Comment by mediaminister** [comment]
I was completely wrong,  I think the bug is related to the Unified Origin streaming platform that is responsible for returning a time bounded manifest file from a live stream url.

**Comment by dagwieers** [comment]
One limitation of inputstream.adaptive is that it does not redownload and re-evaluates the manifest. Most if the webplayers do this (as we noticed with the 404/429 error on missing subtitles).

**Comment by michaelarnauts** [comment]
> One limitation of inputstream.adaptive is that it does not redownload and re-evaluates the manifest. Most if the webplayers do this (as we noticed with the 404/429 error on missing subtitles).

Can't you set inputstream.adaptive.manifest_update_parameter to full? That should redownload the manifest. I had to do this for vtm go.

**Comment by mediaminister** [comment]
Same behaviour on https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html and https://shaka-player-demo.appspot.com/demo/

Tried with a subclip with start and end timestamp: https://live-radio-cf.lwc.vrtcdn.be/groupa/live/e96793cc-eac5-4ed2-8eb5-617c2f6abc55/live.isml/.mpd?t=2020-07-20T07:04:05-2020-07-20T07:30:00
and only a start timestamp: https://live-radio-cf.lwc.vrtcdn.be/groupa/live/e96793cc-eac5-4ed2-8eb5-617c2f6abc55/live.isml/.mpd?t=2020-07-20T07:04:05

The subclip with only a start timestamp doesn't start at the timestamp but starts at the live edge.

So, I suspect VRT NU's web player has a custom implementation that doesn't follow the MPEG-DASH standard.

**Comment by mediaminister** [comment]
InputStream Adaptive handles these streams in the same way the other (web) players do. All players start a stream with a single start timestamp at the live edge but I found out you can manually seek to the start timestamp.

A possible solution/workaround for this issue is to add `self.seekTime(0)` in `onAVStarted` in playerinfo.py and remove the virtual subclip workaround in streamservice.py
This ensures the stream automatically starts playing at the start timestamp while InputStream Adaptive keeps downloading new live segments.
The problem is that I can't detect if a stream url has a single start timestamp in the url with the Kodi Python API in playerinfo.py

Any help is welcome.

**Comment by mediaminister** [comment]
I completely forgot that `xbmc.Player.getPlayingFile()` returns the actual streaming manifest url, so fixing this was a lot easier than I thought.
