### ISSUE TITLE
Unable to play anything

### ISSUE THREAD

**Issue by Undeadhunter** [add-ons/plugin.video.vrt.nu#32]
Please use this template, it really helps me to tackle bugs more easily when everything is filled in a structural manner

**Describe the bug**
Unable to play back anything

**To Reproduce**
Select any video/episode

**Expected behavior**
Episode start playing

**(please complete the following information):**
 - Operating system: Ubuntu LTS 16.04
 - Kodi Version: 17.6

**Log (if available)**

```
19:13:51.829 T:139932420916992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('targetUrls',)
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/addon.py", line 43, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/addon.py", line 36, in router
                                                vrt_player.play_vrtnu_video(params['video'])
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py", line 79, in play_vrtnu_video
                                                stream = self._url_toStream_service.get_stream_from_url(url)
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py", line 75, in get_stream_from_url
                                                hls = self.__get_hls(stream_response.json()['targetUrls'])
                                            KeyError: ('targetUrls',)
                                            -->End of Python script error report<--
19:13:51.847 T:139935353534848   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vrt.nu/?action=play&video=%2Fvrtnu%2Fa-z%2Ftomorrowland%2F2018%2Ftomorrowland-s2018-studio-brussel-brengt-eerbetoon-aan-avicii-op-tomorrowland%2F]
19:14:08.156 T:139935353534848   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
19:14:21.880 T:139932274243328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('targetUrls',)
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/addon.py", line 43, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/addon.py", line 36, in router
                                                vrt_player.play_vrtnu_video(params['video'])
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py", line 79, in play_vrtnu_video
                                                stream = self._url_toStream_service.get_stream_from_url(url)
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py", line 75, in get_stream_from_url
                                                hls = self.__get_hls(stream_response.json()['targetUrls'])
                                            KeyError: ('targetUrls',)
                                            -->End of Python script error report<--
19:14:21.907 T:139935353534848   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vrt.nu/?action=play&video=%2Fvrtnu%2Fa-z%2Fthuis%2F24%2Fthuis-s24a4461%2F]
19:14:24.583 T:139935353534848   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/?action=listingvideos&video=%2fvrtnu%2fa-z%2fthuis.relevant%2f
19:14:24.584 T:139935353534848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/?action=listingvideos&video=%2fvrtnu%2fa-z%2fthuis.relevant%2f) failed
19:14:25.091 T:139935353534848   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/?action=listingaz
19:14:25.092 T:139935353534848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/?action=listingaz) failed
19:14:25.613 T:139935353534848   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/
19:14:25.613 T:139935353534848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/) failed
```

**Comment by pietje666** [comment]
Installed Ubuntu LTS 16.04 and debugged through code. But it worked :/, then installed Kodi and installed addon through Repository and everything also worked. So i am kinda having issues solving this. I would like to see the result of "stream_response.json()" to see if you get a correct response at all.

**Comment by Undeadhunter** [comment]
Let me know how to get this, and I'll get it to you

**Comment by pietje666** [comment]
I will give you a new version with some logging statements most likely tonight

**Comment by pietje666** [comment]
[plugin.video.vrt.nu.zip](https://github.com/pietje666/plugin.video.vrt.nu/files/2421347/plugin.video.vrt.nu.zip)

Please download the folowing zip and enable "Debug logging" in Kodi. Then sent the output of the log after trying to watch something.

**Comment by wim-** [comment]
For info, I have the same problem. Also running Kodi 17.6 from June 2018 running on osmc 2018.08-2. I was able to play back video up until sept 20th before version 1.4.0. The livestreams still work.

**Comment by TASSDevon** [comment]
I'm also having trouble playing anything on OSMC when using version 1.4.1
It says to check the log but not where to find it. If you tell me where it ends up I can paste it here.
Been using the addon for ages, would like to help getting it back up and running on OSMC (on rPi 3).

**Comment by pietje666** [comment]
[plugin.video.vrt.nu.zip](https://github.com/pietje666/plugin.video.vrt.nu/files/2430659/plugin.video.vrt.nu.zip)

@TASSDevon please enable debug logging and show the output using the version im sending in this post. Note do not paste the debug log of that version here but contact me on facebook and send me a private message https://www.facebook.com/kodivrtnu/?ref=br_rs . (The reason for this is that i am logging some login info in this debug log, i do not want other people to see your login tokens etcetera,).  I am not logging your password

**Comment by TASSDevon** [comment]
I just created a new account, activated it and updated the VRT NU plugin with the new user/pass, still doesn't work here.

**Comment by pietje666** [comment]
@TASSDevon  can you contact me on facebook

**Comment by smartathome** [comment]
I got this as well on Kodi 18.12 running on RPi3. The solution was to delete the password in the options page and re-enter it directly again. Seems like there is a password cache or session problem.

**Comment by pietje666** [comment]
> I got this as well on Kodi 18.12 running on RPi3. The solution was to delete the password in the options page and re-enter it directly again. Seems like there is a password cache or session problem.

This is was an issue on Version 1.5.1 tokens would get stored in a wrong format, from version 1.5.2 this is fixed but to reset the token it is indeed necesarry to adjust something in the settings.
