### ISSUE TITLE
Movie/Episode year is taken from 'aired' metadata

### ISSUE THREAD

**Issue by dagwieers** [add-ons/plugin.video.vrt.nu#401]
### Describe the bug ###
The Information-pane of a movie or episode always shows the current year, rather than the year we have set. This is because the Kodi skin seems to prefer using the `aired` date rather than the `premiered` information or the `year` infoLabel.

Obviously when we use the `aired` date, it is not the original aired date of the episode, but the date it was aired on VRT or publicized on VRT NU and this was likely not the intended use. However if there's also a `year` infoLabel, it should be using that above all else.

IMO this is a bug in the implementation, or Kodi should be extended with video-on-demand use-cases.

### Additional context ###
- Operating system: LibreELEC v9.0.2
- Kodi version: Kodi v18.2
- Addon version: v2.1.1
- Using a VPN: no
- Country you are using the addon from: BE

**Comment by mediaminister** [comment]
VRT Search API doesn't provide the original release dates, so this bug is of no importance for the add-on

**Comment by dagwieers** [comment]
It does for movies. Most (if not all) movies have the release year as the season. That is why I wanted to do this:
https://github.com/dagwieers/plugin.video.vrt.nu/blob/165d3f821cd20d8c5de24c011493153b623593e1/resources/lib/apihelper.py#L395-L399

**Comment by dagwieers** [comment]
I reported this issue here: xbmc/xbmc#16486

**Comment by mediaminister** [comment]
I fixed this in https://github.com/xbmc/xbmc/pull/17217
