### ISSUE TITLE
Support subtitle colours

### ISSUE THREAD

**Issue by dagwieers** [add-ons/plugin.video.vrt.nu#688]
### Describe the feature ###
The subtitles provided by VRT NU include colouring, however this is currently not supported by **inputstream.adaptive**'s TTML support.

To make this work, **inputstream.adaptive** needs to support "span tss:color" in TTML subtitles.

Experimental support was added by @mediaminister and is found here: https://github.com/mediaminister/inputstream.adaptive/commit/fca16d9f1d9c63d6df05b0de202f74029e2f7cfe#commitcomment-37308739

**Comment by dagwieers** [comment]
I reported this upstream at peak3d/inputstream.adaptive#386

**Comment by alpagu37** [comment]
Hello, could you please help mo to find a way to save the subtitle file from VRT NU in order to use them for my ANKI Nederlands Flashcards project?

**Comment by mediaminister** [comment]
I fixed this in https://github.com/peak3d/inputstream.adaptive/pull/442

**Comment by dagwieers** [comment]
This is now available in IA 2.4.5 (Leia) and IA 2.6.0 (Matrix). Thanks @mediaminister !
