### ISSUE TITLE
Add-on not working in Kodi v19 (Matrix) anymore

### ISSUE THREAD

**Issue by mediaminister** [add-ons/plugin.video.vrt.nu#692]
Since Team Kodi merged https://github.com/xbmc/xbmc/pull/17188, the VRT NU add-on was removed from the official Kodi 19 Matrix repository.

Installing the VRT NU add-on from zip file in Kodi 19 Matrix is also not possible anymore with the latest nightly builds from March 2020 onwards. The last compatible nightly is **Kodi 19.0-ALPHA1 Git:20200226-cde760b94e**

Despite the VRT NU add-on is fully compatible with both Python 2 and Python 3, Team Kodi now demands that we make two separate releases and submissions, one for the Kodi 19 Matrix repository and one for a Kodi 18 or earlier repository.

To get the VRT NU add-on accepted in Kodi 19 Matrix repository, we have to maintain a separate branch with a different **addon.xml** containing `<import addon="xbmc.python" version="3.0.0"/>`

For Kodi 18 and earlier we need to preserve the current **addon.xml** with `<import addon="xbmc.python" version="2.25.0"/>`

In my opinion submitting the add-on twice and maintaining two separate branches is a completely stupid workflow since the VRT NU add-on is fully compatible with both Python 2 and Python 3 and should just work on Kodi 17, Kodi 18 and Kodi 19 with a single repository submission.

Using a single **addon.xml** with an xml tag that marks compatibility with both Python 2 and Python 3 is the only right solution for this problem. It ensures we can preserve our current workflow and we only have to submit the add-on once every new release.

This breaking change came  as a total surprise for me. There wasn't any communication from Team Kodi to add-on developers beforehand (besides a two weeks old forum thread).

You can find the discussion about this breaking change at the following links:
https://forum.kodi.tv/showthread.php?tid=351745 and https://github.com/xbmc/xbmc/issues/17326

**Comment by dagwieers** [comment]
Requiring 2 branches and 2 separate zip files for the exact same content while most add-on devs already invested in a single py2/py3 codebase to offer the best upgrade path is silly at best.

I would rather keep it blocking a release until this gets fixed, than to have to support the fallout of this change.

**Comment by dagwieers** [comment]
The following add-ons are currently missing in Matrix:
- script.module.inputstreamhelper
- script.module.routing
- service.upnext

**Comment by mediaminister** [comment]
Fixed with the v2.3.3 release.
