### ISSUE TITLE
autostart kodi with live stream of Eén Live

### ISSUE THREAD

**Issue by reneverlinden** [add-ons/plugin.video.vrt.nu#695]
### Describe the feature ###

I would start kodi with playing the livestream of Eén live of Vrt.nu. I wrote 
the next command  for obtaining this (first: import xbmc) in autoexec.py :
xbmc.executebuiltin('XBMC.RunAddon(plugin.video.vrt.nu,/play/url/https://www.vrt.be/vrtnu/kanalen/een/een-live)')  I 've placed this file in userdata and when kodi starts, there doesn't come an error message  , but after a while a message appears on the screen : "... dit vereist een account bij vrt.nu... "
the same occurs when I want start kodi with playing an item of a-z;. In kodi the addon Vrtnu performs correctly and I have a valid vrtnu account .
could you say please what's the reason that this happens ?

**Comment by mediaminister** [comment]
`RunAddon` is the wrong function, you should use `PlayMedia`. It is currently not possible to play the livestreams from a VRT NU url. You can only play livestreams using the `live_stream_id`.

The following code will work:

```python
import xbmc
xbmc.executebuiltin('PlayMedia(plugin://plugin.video.vrt.nu/play/id/vualto_een_geo)')
```

**Comment by dagwieers** [comment]
This is now documented in our Wiki at: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Automation#start-playing-live-tv

**Comment by reneverlinden** [comment]
Thanks!

**Comment by dagwieers** [comment]
@reneverlinden Do you have more information to why you reopened this issue?

**Comment by reneverlinden** [comment]
Beste,

Excuseer, ik was gewoon aan het kijken wat ik toen geschreven had, want ik ben eigenlijk op zoek naar een instructie voor kodi op te starten (via autoexec.py)  met vtm of met vtm2…. analoog met wat ik toen gevraagd had om kodi op te starten met vrt.nu 

Hoogachtend,
René Verlinden

Verzonden vanuit Mail voor Windows 10

Van: Dag Wieers
Verzonden: donderdag 21 januari 2021 15:34
Aan: add-ons/plugin.video.vrt.nu
CC: reneverlinden; Mention
Onderwerp: Re: [add-ons/plugin.video.vrt.nu] autostart kodi with live stream of Eén Live (#695)

@reneverlinden Do you have more information to why you reopened this issue?

**Comment by dagwieers** [comment]
@reneverlinden Then I will close this ticket again :+1: 
For the VTM GO add-on, you may want to open a ticket at: https://github.com/add-ons/plugin.video.vtm.go/issues
