### ISSUE TITLE
OSD missing episode number/title and 'airdate'

### ISSUE THREAD

**Issue by piejanssens** [add-ons/plugin.video.vrt.nu#783]
### Describe the bug ###

<img width="1680" alt="Schermafbeelding 2020-06-18 om 11 45 27" src="https://user-images.githubusercontent.com/829098/85009299-85ea7a00-b15e-11ea-8db8-27af48d42775.png">

### To Reproduce ###
1. Play VOD episode
2. Press I to display the OSD information

### Expected behavior ###
View similar info available in the episode list views.

### Additional context ###

- Kodi version: 18.7
- Addon version: 2.3.5
- Skin: Arctic Horizon

**Comment by mediaminister** [comment]
Should be fixed in the master branch. Please try this zip package:
[plugin.video.vrt.nu-2.3.5-master-17ebe76.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/4798270/plugin.video.vrt.nu-2.3.5-master-17ebe76.zip)

**Comment by piejanssens** [comment]
I now tested 2.3.5 and see the same issue and after further testing the issue does not seem to be present in Estuary... 

https://github.com/jurialmunkey/skin.arctic.horizon

**Comment by mediaminister** [comment]
Can you provide some more details how to reproduce this? From which menu did you play the VOD episode?

**Comment by piejanssens** [comment]
My Favorites -> My Programs -> "Ten Oorlog" > "Season 1" -> select episode

**Comment by mediaminister** [comment]
Okay, I can reproduce this.

**Comment by mediaminister** [comment]
@piejanssens Please test and report if this fixes this issue.
[plugin.video.vrt.nu-2.3.5-seasons-f49e3e0.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/4800233/plugin.video.vrt.nu-2.3.5-seasons-f49e3e0.zip)

**Comment by piejanssens** [comment]
It does! Looks great, thanks.
