### ISSUE TITLE
Support 'watched' indicator

### ISSUE THREAD

**Issue by piejanssens** [add-ons/plugin.video.vrt.nu#784]
### Describe the feature ###

I would like to see the 'watched' indicator on episodes that I watched and it would also be useful to be able to 'mark as watched'.

**Comment by dagwieers** [comment]
In most cases this should work as expected, but there are technical difficulties to synchronize Kodi with the information from VRT NU.

I think this is a duplicate of: #568

**Comment by piejanssens** [comment]
Yes, indeed duplicate. Thanks.

**Comment by mediaminister** [comment]
You can disable "Watching activity" in the VRT NU add-on interface settings. This restores the normal Kodi watch status/mark as watched function, but disables resumepoints synchronization with VRT NU website.
