### ISSUE TITLE
Cannot enter account credentials

### ISSUE THREAD

**Issue by vdkeybus** [add-ons/plugin.video.vrt.nu#792]
### Problem ###

I cannot play non-live content. Live content works.

Contrary to documentation, there is no dialog or similar to enter account data. The window that is most likely containing this data to fill in, has no entries.

### To Reproduce ###

VRT NU installed from repository without issues. Try to watch.

### Expected behavior ###

Where to set the account credentials ?

### Additional context ###
- Operating system: Ubuntu 20.04
- Kodi version: 18.7
- Addon version: ?
- Using a VPN: yes/no no
- Country you are using the addon from: ... BE

**Comment by michaelarnauts** [comment]
You can find this in the add-on settings. This can be opened by using the context menu on the VRT Nu icon in your Addons list.

**Comment by mediaminister** [comment]
Do you use a special skin in Kodi? Normally, the add-on settings dialog opens automatically when trying to play a on demand video when no (or wrong) user credentials are filled in.

**Comment by vdkeybus** [comment]
Dialog opens but no entries.

This is as stock as can be, even running as separate user as service. No
window manager.

**Comment by dagwieers** [comment]
Maybe a screenshot and debug log could be helpful?

**Comment by vdkeybus** [comment]
I changed the theme of the Estuary skin, and then the options become
visible.

Will try to get screenshot and log today.

**Comment by mediaminister** [comment]
> I changed the theme of the Estuary skin, and then the options become visible.

This means this problem was related to another skin? Can you specify which skin?

**Comment by vdkeybus** [comment]
It is the one you get when installing Kodi. It is apparently called
Estuary, but I needed to change its theme to get the menu entries to show
up. The theme was default and I just changed the color to green.

**Comment by mediaminister** [comment]
I don't think this can be fixed in the VRT NU add-on. 
Themes and skins are managed in Kodi, a screenshot would be very helpful to determine if this is a real bug.

**Comment by mediaminister** [comment]
Feel free to reopen this if you have more information about this problem. If this issue is documented it should be reported to the Estuary skin developers at https://github.com/xbmc/xbmc/issues
