### ISSUE TITLE
Add 'Live' channels to PVR channel list

### ISSUE THREAD

**Issue by herrJones** [add-ons/plugin.video.vrt.nu#795]
Ik zag dat dit ooit op de lijst stond maar het 'issue' is ondertussen gesloten.

Het zou handig zijn mochten de 'live' kanalen van VrtNU (en bij uitbreiding: VtmGo) in de lijst van de PVR radio + tv stations zouden staan.
Op die manier zou dat mooi integreren met de satelliet FTA kanalen die ik binnen krijg via de TVHeadend PVR plugin.

Ik las de workaround via IPTV Merge en IPTV Simple maar dan is er wel nog steeds een M3U lijst nodig.

Groeten,

   Jan

**Comment by herrJones** [comment]
... en dan vind ik net een 'channels.m3u8' in de code...

**Comment by michaelarnauts** [comment]
Ik raad je aan om naar dit (jonge) project van ons te kijken: https://github.com/add-ons/service.iptv.manager

Dit doet exact wat je zegt, en het blijft ook werken met tvheadend (Kodi ondersteund meerdere PVR Addons).

Voor VTM Go moet je wel de laatste master uit GitHub gebruiken, in VRT Nu is dit al geïntegreerd in de recente release.

**Comment by herrJones** [comment]
OK, bedankt, ik kijk er morgen eens naar!
Mijn partner is al van de wijs omdat de icoontjes 2 plaatsjes verschoven zijn :-D

**Comment by dagwieers** [comment]
Ticket #209 (Add TV livestreams to an IPTV PVR client) werd automatisch gesloten omdat PR #737 (Add support for IPTV Manager) aan de code werd toegevoegd. Dus dat "issue" was effectief opgelost en niet meer nodig.

**Comment by herrJones** [comment]
workaround via ipv manager lijkt te werken!
Thnx guys
