### ISSUE TITLE
playback has hiccups when playing using inputstream adaptive

### ISSUE THREAD

**Issue by edd--** [add-ons/plugin.video.vrt.nu#802]
playback has hiccups when playing using inputstream adaptive with the latest version of IA, is there a way to play 720p streams without input stream.adaptive ? If I disable IA the streams seem to be limited to 540p ...

I'm running Kodi 18.7 on coreelec 9.2.3 on a odroid N2 device.

**Comment by mediaminister** [comment]
Yes, if you disable "Use Widevine DRM" in the VRT NU add-on "Playback" settings, you can watch 720p livestreams without InputStream Adaptive.
VRT only offers the livestreams in 720p, on demand streams are offered in 540p.

Does a previous version of InputStream Adaptive work without hiccups? Which version? Maybe you can open an issue for this at https://github.com/peak3d/inputstream.adaptive/issues

**Comment by edd--** [comment]
on demand streams also seem to stream at 720p when using input stream adaptive ? At least that's what the info in Kodi tells me. Or do you think it is being upscaled ?

**Comment by mediaminister** [comment]
No, only live broadcasted current affair programs like "Terzake" are streamed in 720p while and shortly after the live broadcast. This is because the "on demand" stream is automatically generated from the livestream.
Normally, all other "on demand" programs are 540p.

**Comment by edd--** [comment]
ah, I see, well I mainly use the plugin to stream the news so that makes
sense. Any way to stream those without inputstream adaptive in 720p ?
Because when I stream the news without IA it streams at 540p, streaming the
same file with IA it streams at 720p ...

**Comment by mediaminister** [comment]
> Any way to stream those without inputstream adaptive in 720p?

Normally, you don't need InputStream Adaptive to get all livestreams in 720p. I'll check if there is a bug with the live-to-VOD functionality for live broadcasted current affair programs.

**Comment by mediaminister** [comment]
There was indeed a bug with the live-to-VOD functionality and HLS streams.
Fixed in this package
[plugin.video.vrt.nu-2.4.0-subclip720p-07a8c18.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/5027979/plugin.video.vrt.nu-2.4.0-subclip720p-07a8c18.zip)

The fix will be included in the next 2.4.1 release.

**Comment by edd--** [comment]
Thanks, but I tried to install this package and I still get 540p when I
disable inputstream adaptive on news emissions ... I did get a notice the
addon was updated though.

**Comment by dagwieers** [comment]
If you update an add-on, the old version is still in memory. You either have to restart Kodi, or load another add-on to purge the old VRT NU add-on from memory.

**Comment by mediaminister** [comment]
With this fix, you get 720p for current affair programs  **but only during and shortly after the live broadcast**. When VRT uploads the "on demand" stream, you always get 540p.

**Comment by edd--** [comment]
ok, tested and works ! no more issues now, thanks !
