### ISSUE TITLE
Add VRT NU search to Custom Search Lists

### ISSUE THREAD

**Issue by vermope** [add-ons/plugin.video.vrt.nu#813]
### Describe the feature ###

In jurialmunkey's skins Arctic Horizon/Zephyr it is possible to add custom search list for external add-ons.
Since VRT NU, VTM GO and VIER-VIJF-ZES, have a search function, is it possible to provide the right path/query for this?

See here: https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/36

**Comment by mediaminister** [comment]
You can use plugin://plugin.video.vrt.nu//search/query/<keywords>

This is documented at: https://github.com/add-ons/plugin.video.vrt.nu/wiki/Automatisatie

**Comment by vermope** [comment]
@mediaminister Thanks, by entering this I've got it working: "plugin://plugin.video.vrt.nu/search/query/"

For VTM GO and VIER-VIJF-ZES, it seems that this doesn't work like this, should I do a request in the designated git?

**Comment by vermope** [comment]
@mediaminister Got it working for VTM GO and VIER-VIJF-ZES:
plugin://plugin.video.vtm.go/search/
plugin://plugin.video.viervijfzes/search/

Thanks for getting me in the right direction!

**Comment by dagwieers** [comment]
I once looked at providing our own search entries in Kodi, but it wasn't possible for an add-on to add this automatically.

It would be a nice feature for Kodi to allow this. One search doe a configurable list of add-ons.
