### ISSUE TITLE
Seasons missing from Thuis

### ISSUE THREAD

**Issue by Undeadhunter** [add-ons/plugin.video.vrt.nu#835]
### Describe the bug ###
Thuis is missing certain seasons, only the available seasons up til 16 show up 

### To Reproduce ###
Go to the series page either through favorites or manually

### Expected behavior ###
See the followign seasons in the list
Seizoen 26
Seizoen 25
Seizoen 23

### Additional context ###

- Operating system: Andoid
- Kodi version: 18.9
- Addon version: 2.4.1
- Using a VPN: no
- Country you are using the addon from: BE

**Comment by mediaminister** [comment]
I have an experimental fix, please test:
[plugin.video.vrt.nu-2.4.1-seasons-b598413.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/5685385/plugin.video.vrt.nu-2.4.1-seasons-b598413.zip)
