### ISSUE TITLE
Favourites partially visible in menu

### ISSUE THREAD

**Issue by badoneti** [add-ons/plugin.video.vrt.nu#838]
### Describe the bug ###
I have over time 21 favorites marked in VRTNU website of which there are 7 programmes and series still available to watch on VRTNU. When I browse my favorite programmes via the add-on menu, I only find 4 of the 7 current favorites. 

### To Reproduce ###
1. Go to Mijn favorieten
2. Click on Mijn programmas
4. See 4 entries

Check add-on settings; 
Go to Manage favorites: 21 entries from which 7 are active (green color)

### Expected behavior ###
1. Go to Mijn favorieten
2. Click on Mijn programmas
4. See all 7 entries

### Additional context ###

- Operating system: LibreElec 9.2.6
- Kodi version: 18.9 (leia)
- Addon version: 2.4.1
- Using a VPN: no
- Country you are using the addon from: BE

**Comment by mediaminister** [comment]
Can you try the following:
- Go to Mijn favorieten > Mijn programmas
- Open [Kodi's context menu](https://kodi.wiki/view/Basic_controls#Context_Menu)
- Choose "Ververs menu"

Do the above instructions solve the problem?

**Comment by badoneti** [comment]
No, I tried this and it doesn't change. I also tried clearing VRT tokens etc.

**Comment by mediaminister** [comment]
Okay, I'll investigate. Can you specify at least one favourite program that is not shown in the menu?

**Comment by badoneti** [comment]
Visible:
- Black out
- Das Boot
- Good will hunting (recently marked and appeared)

Not visible:
- Cardinal
- Exit (recently marked)
- Geubels en de hollanders (recently marked)

**Comment by mediaminister** [comment]
Thanks for the info, I can reproduce this problem and I'll find a solution.

**Comment by badoneti** [comment]
Thanks!

**Comment by mediaminister** [comment]
Seems like a VRT NU bug, the API sometimes returns a wrong `programUrl` ending with `.html`
```
programUrl: "/vrtnu/a-z/cardinal.html"
```
I fixed it by removing the `.html` from the programUrl.

Please test with the following zip package: 
[plugin.video.vrt.nu-2.4.1-seasons-b598413.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/5715703/plugin.video.vrt.nu-2.4.1-seasons-b598413.zip)

**Comment by badoneti** [comment]
I didn't notice a difference, not after restart and refreshing explicitly the favorites from the add-on settings.
Note that in the addon setting Manage favorites, I can (could already before) see all favorites. It's only when browsing to the favorites where they don't appear all of them.

**Comment by mediaminister** [comment]
I'm sorry, I uploaded a wrong package.
This should work: 
[plugin.video.vrt.nu-2.4.1-favourites-ec54610.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/5716532/plugin.video.vrt.nu-2.4.1-favourites-ec54610.zip)

**Comment by badoneti** [comment]
Ja, dit werkt perfect!


Op vr 18 dec. 2020 om 16:27 schreef mediaminister <notifications@github.com>
