### ISSUE TITLE
Episode starten terwijl die nog live bezig is geeft geen mogelijkheid om te starten vanaf het begin

### ISSUE THREAD

**Issue by kstr** [add-ons/plugin.video.vrt.nu#846]
Episode starten terwijl die nog live bezig is geeft geen mogelijkheid om te starten vanaf het begin.  Dit lukt wel in de officiële app.

Reproduceren:
1. Kies om 19:30 'Journaal 19u'
2. "Afspelen"
3. Je krijgt de live beelden zonder mogelijkheid om terug te spoelen

Verwachte gedrag:
Afspelen vanaf het begin.

**Comment by mediaminister** [comment]
Dit werkt normaalgezien wel als je bij Add-on instellingen in de categorie Afspelen "Gebruik Widevine DRM" aanzet.

Indien mogelijk kan je dat straks al uittesten tussen 13u en 13u25 of 19u en 19u41

Ik zal eens nakijken hoe ik dit standaard kan instellen zodat het automatisch voor elke gebruiker werkt.

**Comment by michaelarnauts** [comment]
@kstr Is dit als je afspeelt via de TV gids in Kodi (dus met IPTV Manager)? Kodi verkiest live boven vod. Dit is instelbaar via de instellingen van de Gids (in Kodi zelf). Zie https://github.com/xbmc/xbmc/pull/11782 voor een duidelijke omschrijving.

Je kan hier ook omheen werken door via het contextmenu "Afspelen via IPTV Manager" te kiezen.

**Comment by kstr** [comment]
Hallo.  Bedankt voor de verduidelijking.  De link tussen Widevine DRM en het gedrag had ik niet gemaakt.  Na het opzetten lukt het inderdaad wel.  Het gaat voor alle duidelijkheid niet over het starten via de tv gids, maar op dezelfde manier als een aflevering uit het verleden starten.
