### ISSUE TITLE
timeshift functionality 

### ISSUE THREAD

**Issue by siemon-geeroms** [add-ons/plugin.video.vrt.nu#854]
Hi, 

Maybe it's a technical limitation but why is Kodi not allowing/able to pause a live stream?
or is it a setting that I'm overlooking?

thanks in advanced,

Siemon

**Comment by dagwieers** [comment]
It works fine here. Can you describe a bit more what you are doing?

**Comment by siemon-geeroms** [comment]
When watching the één live stream via de VRT nu add-on on kodi 18 (libreelec) I only have the option to stop the stream but not pause it.

I will have a look at that setting you mentioned later this evening.

**Comment by siemon-geeroms** [comment]
Ok the InputStream Adaptive add-on was not even installed. after installing and enabling it in the add-on I can pause live streams. Thanks for your help!

**Comment by dagwieers** [comment]
Thanks for reporting, I didn't even know pause was not working on live streams without ISA.

We now have a record of it 😉
