### ISSUE TITLE
Radio plus support

### ISSUE THREAD

**Issue by JeanPoll** [add-ons/plugin.video.vrt.nu#859]
It would be nice to have a radio plus plugin/addon like vrt nu iso of only live radio stream.

**Comment by michaelarnauts** [comment]
You'll need to install the VRT Radio Add-on for that.

See https://kodi.wiki/view/Add-on:VRT_Radio

**Comment by dagwieers** [comment]
Duplicate of https://github.com/add-ons/plugin.audio.vrt.radio/issues/15
