### ISSUE TITLE
Canvas 

### ISSUE THREAD

**Issue by Rvhalewyn** [add-ons/plugin.video.vrt.nu#860]
Hallo, geweldige add-on.
1 issue: Canvas non-live speelt bij mij met horten en stoten af. Echt alleen Canvas,en alle programma's. 
Kodi 18.9 op LIBREELEC 9.2.5

**Comment by mediaminister** [comment]
Probeer eens of "Gebruik Widevine DRM" in de add-on settings bij "Afspelen" aan of uit het probleem oplost.
Geef ook eens een tijdstip en of programma, zodat ik eens kan uittesten of ik dit probleem kan reproduceren.

**Comment by Rvhalewyn** [comment]
Dank u wel, ik schakelde Widevine in, en geen probleem meer.

Planet of Treasures, van gisteren. 

Met vriendelijke groeten
Rudy Vanhalewyn
Contactpersoon voor België van
Stichting Projecthulp Suriname
Winston Churchilllaan 23 bus 14
B-8300 Knokke-Heist

tel. +32 50 94 61 28 of +32 496 84 72 74
tel. vanuit Suriname 750 37 47
tel. vanuit Nederland +31 6 377 22 746
Viber +316 377 22 746
WhatsApp +316 377 22 746
sip:rvhalewyn@pbxes.org 
LinkedIn Rudy Vanhalewyn


-------- Origineel bericht --------
Van: mediaminister <notifications@github.com>
Verzonden: 1 maart 2021 14:42:07 CET
Aan: "add-ons/plugin.video.vrt.nu" <plugin.video.vrt.nu@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [add-ons/plugin.video.vrt.nu] Canvas  (#860)

Probeer eens of "Gebruik Widevine DRM" in de add-on settings bij "Afspelen" aan of uit het probleem oplost.
Geef ook eens een tijdstip en of programma, zodat ik eens kan uittesten of ik dit probleem kan reproduceren.
