### ISSUE TITLE
Playback 12+ content fails

### ISSUE THREAD

**Issue by yorickps** [add-ons/plugin.video.vrt.nu#882]
### Describe the bug ###

When trying to play series labeled as 12+, Kodi/plugin fails to play the episode with following error message.
I've checked my kodi settings, it does not have Parental Control enabled.

```bash
FATAL <general>: [plugin.video.vrt.nu] Age category 0+ is not allowed to access 12+ content
```

### To Reproduce ###

1. Go to Series
2. Click on any series that has the 12+ label (e.g. Petra, Riviera,...)
3. Start an episode
4. See following error: Whoops something whent wrong, check kodi.log for more info

Kodi log shows 

```bash
FATAL <general>: [plugin.video.vrt.nu] Age category 0+ is not allowed to access 12+ content
```

### Expected behavior ###

Play the episode without errors.

### Additional context ###

- Operating system: Debian testing (bullseye) 5.10.0-3-amd64 
- Kodi version: kodi 2:19.0+dfsg1-1 amd64 
- Addon version: 2.5.2+matrix.1
- Country you are using the addon from: Belgium

### Log (if available) ###

```bash
2021-05-12 22:12:13.741 T:4101     INFO <general>: CPythonInvoker(4, /home/yorick/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
2021-05-12 22:12:15.844 T:4101     INFO <general>: initializing python engine.
2021-05-12 22:12:16.123 T:4101    FATAL <general>: [plugin.video.vrt.nu] Age category 0+ is not allowed to access 12+ content
```

**Comment by michaelarnauts** [comment]
Is your birthday correct on your VRT profile? https://profiel.vrt.be/mijn-gegevens

**Comment by mediaminister** [comment]
I can't fix this, age restrictions are VRT NU policy. VRT NU returns ERROR_AGE_RESTRICTED when your VRT NU account doesn't contain a valid birth date. With a VRT NU account that lacks a valid birth date, you can only play content that has no age restriction. 

I added a better error message that asks the user to check their VRT NU account at https://www.vrt.be/vrtnu

**Comment by mediaminister** [comment]
I fixed this by requesting a user X-VRT-Token for all on demand content. So, the legacy X-VRT-Token is becoming as good as useless.
