### ISSUE TITLE
Kodi crasht bij het starten van Ketnet Junior Live

### ISSUE THREAD

**Issue by henkv1** [add-ons/plugin.video.vrt.nu#889]
Bij het starten van Ketnet Junior Live crasht Kodi nog voordat de uitzending gestart is. Ik heb ditzelfde probleem op twee verschillende Kodi installaties.
Het systeem is een Raspberry Pi 4 met Kodi 19.1 en VRT.Nu v2.5.3+matrix1

**Comment by henkv1** [comment]
[kodi.log](https://github.com/add-ons/plugin.video.vrt.nu/files/6602552/kodi.log)

**Comment by peno64** [comment]
Ik denk dat je de laatste versie van kodi moet downloaden en widevine updaten. Hier geen probleem op mijn pi4 met kodi 19.1. Merk op dat  de laatste versie van libreelec een manuele update is tbv widevine en dat is nog steeds kodi 19.1 
LibreELEC-RPi4.arm-9.95.4

**Comment by peno64** [comment]
O ja en voor kodi 19 moet je ook een configuratie file aanmaken. Zie https://libreelec.tv/2021/05/le-9-2-7-10b4-fix-widevine/

**Comment by mediaminister** [comment]
Ik heb het nagekeken. De stream van Ketnet Junior is momenteel niet meer beveiligd met Widevine DRM terwijl dit wel zo aangegeven staat in het MPEG-DASH manifest. Dat is in principe een fout bij de livestream van VRT NU waar de Kodi-speler niet mee om kan.

Als voorlopige oplossing kan je Widevine DRM uitschakelen in de VRT NU Add-on.

Ik bekijk later nog of ik voor dit probleem een goede workaround kan vinden.

**Comment by peno64** [comment]
@mediaminister Ik heb geen probleem met  afspelen van ketnet en widevine is aktief in de vrt nu instellingen. En widevine werkt ook want de live streams van één, canvas, vtm en zo spelen allemaal af. Kan het  zijn dat de laatste widevine versie daar geen probleem mee heeft en de vorige wel? Ik zit ook op kodi 19.1 op een pi4 met libreelec (9.95.4 welke aangepast is voor de nieuwste widevine)

**Comment by mediaminister** [comment]
Dit probleem treft uitsluitend Ketnet **Junior** dat gebruiktmaakt van een andere streamingprovider.

**Comment by peno64** [comment]
@mediaminister Om volledig te zijn. Ketnet Junior live werkt hier dus ook prima met Widevine DRM geactiveerd. Net nog eens geprobeerd en geen problemen

**Comment by mediaminister** [comment]
Aha, het probleem kan ook afhangen van de InputStream Adaptive versie. Welke versie gebruik jij?

**Comment by peno64** [comment]
2.6.8.1

Inputstream helper geeft  volgende info:

![image](https://user-images.githubusercontent.com/32430988/120934845-4961b680-c700-11eb-8c2d-9fc236b2bf36.png)

**Comment by mediaminister** [comment]
Oké, ik zit op 2.6.16 en daarbij doet het probleem zich wel voor.

**Comment by peno64** [comment]
hm ik zie idd op github dat  2.6.16 al sinds 16 dagen de laatste versie is maar als ik kodi laat zoeken naar alle updates dan wordt  die niet  voorgesteld als update. Ik zal die eens manueel installeren (op een bakup sd- kaartje) en zien als ik dan problemen heb.

**Comment by mediaminister** [comment]
Je hoeft niet te testen, 2.6.16 geeft sowieso problemen. Zowel bij mij als bij henkv1

**Comment by peno64** [comment]
Ik krijg em zelfs niet  geinstalleerd. install from zip geeft een fout en dit komt  in de log:

2021-06-06 20:07:05.422 T:1024    ERROR <general>: CAddonInfoBuilder::Generate: Unable to load 'zip://%2fstorage%2fdownloads%2finputstream.adaptive-2.6.16-Matrix.zip/inputstream.adaptive-2.6.16-Matrix/addon.xml', Line 0
                                                   Failed to open file

**Comment by peno64** [comment]
Er is zelfs geen addon.xml file in die zip ...

**Comment by michaelarnauts** [comment]
> Er is zelfs geen addon.xml file in die zip ...

Welke zip heb je gebruikt? Bij de releases is er enkel een source code zip, die is niet gecompileerd.

**Comment by mediaminister** [comment]
Het gaat om een bug in InputStream Adaptive. Het probleem is deze wijziging: https://github.com/xbmc/inputstream.adaptive/commit/10d7f6f6d60678a6e5009a2b72df7ab9bad986c9

**Comment by mediaminister** [comment]
Ik heb deze bug gerapporteerd bij de InputStream Adaptive repo: https://github.com/xbmc/inputstream.adaptive/issues/707

Voorlopige oplossing is dus InputStream Adaptive 2.6.14 of ouder gebruiken. Of Widevine DRM in de VRT NU add-on uitschakelen.

**Comment by peno64** [comment]
Hm. Als ik naar My add-ons ga, InputStream Adaptive, Versions dan zie ik idd nieuwere versies. Om één of andere reden neemt mijn kodi die niet als ik naar nieuwere versie zoek. Hij blijft bij 2.6.8.1
Van zodra ik manueel update naar 2.6.11.1 heb  ik idd ook het probleem.  Keer ik terug naar 2.6.8.1 dan gaat het terug.
Zit het probleem dan niet al in 2.6.11.1 ? Jij zegt namelijk dat 2.6.14 nog zou werken maar niet bij mij dus...

**Comment by mediaminister** [comment]
Ja, op Linux x64 toch. Misschien verschillen versienummers voor ARM.

**Comment by peno64** [comment]
Idd 2.6.14.1 werkt nog na een reboot. 2.6.15.1 idd niet.

Het  blijft me echter wel een raadsel waarom mijn kodi die updates niet zelf voorstelt om te  doen en dat ik ze dus manueel  moet doen. Zelfs al doe ik My add-ons, pijltje naar links, kies daar Check for updates dan stelt hij dus geen updates voor van inputstream.adaptive. Dat is ook de reden waarom ik nog steeds zat op 2.6.8.1

**Comment by mediaminister** [comment]
Fixed in InputStream Adaptive v2.6.17
