### ISSUE TITLE
Some (DRM?) content plays way too fast and audio out of sync. But only so on CoreELEC.

### ISSUE THREAD

**Issue by NofanTasi** [add-ons/plugin.video.vrt.nu#890]
### Describe the bug ###

Series like for example 'The Investigation' are impossible to watch since content plays way too fast and audio out of sync. Perhaps garbled too.

I experience this on CoreELEC 19.x but not on gentoo x86_64 19.x 

Since I do not watch foreaign series a lot I am not even sure when problem started. Sorry for that.

No other addon (like Streamz Yelo VTM-Go or NPO or Netflix) suffers from this, 

I will post issue on CoreELEC as well.

### To Reproduce ###

Play any episode of  'The Investigation'  (or 'Des' or many other) 

### Expected behavior ###

Video and audio should proceed in sync and at normal speed.

### Additional context ###

- Operating system: CoreELEC
- Kodi version: 19.2 rc2
- Addon version: 2.5.3+matrix.1
- Using a VPN: yes/no : no
- Country you are using the addon from: ... Belgium

### Log (if available) ###

 not sure if relevant

2021-06-13 18:07:53.179 T:4054  WARNING <general>: ActiveAE - large audio sync error: -5027.506584
2021-06-13 18:07:53.213 T:4047     INFO <general>: VideoPlayer: OnResetDisplay received
2021-06-13 18:07:53.218 T:4047     INFO <general>: GLES: Maximum texture width: 8192
2021-06-13 18:07:53.233 T:4054  WARNING <general>: ActiveAE - large audio sync error: -5284.532833
... (many WARNING)

**Comment by NofanTasi** [comment]
see also on CoreELEc forum
https://discourse.coreelec.org/t/coreelec-19-2-matrix-rc2-discussion/16020/56

**Comment by mediaminister** [comment]
I need a full debug log to investigate. See https://kodi.wiki/view/Log_file/Easy
I don't own CoreELEC hardware, so I can't test this.

**Comment by NofanTasi** [comment]
dear mediaminister I fully understand your situation
- only VRT-Nu has issues
- only CoreELEC has issues
- only some content has issues (all the ones I know of are foreign series)
I will upload a full log with nothing more and nothing less than a boot and an attempt to play

**Comment by mediaminister** [comment]
You could try to enable Widevine DRM in VRT NU Add-on settings. A different stream will be selected and maybe this will play normally.

**Comment by NofanTasi** [comment]
Dear kind mediaminister. You spotted the issue! It was indeed DRM. Let's close this issue.

**Comment by NofanTasi** [comment]
DRM enable required for DRM content

**Comment by dagwieers** [comment]
We have this documented on the Wiki, please verify if the documentation is still correct, or should be adapted to avoid any confusion: https://github.com/add-ons/plugin.video.vrt.nu/wiki/DRM

**Comment by NofanTasi** [comment]
@dagwieers 
The documentation is correct.
Personally I still don't know when, how or why DRM was disabled. In **worst** case I turned it off myself for some odd reason and then forgot I did so. But if the v1.5.0 introduction of the knob had default **off**, maybe I would perhaps suggest default **on**. Because **off** may confuse people (like me) to believe the odd behaviour may have beeen introduced by a defect rather than by a feature. Alternatively document default ro be **off**.
Keep up the good work!

**Comment by mediaminister** [comment]
There is a defect with HLS-streams and CoreELEC, all VRT NU VOD-streams should work with or without Widevine DRM.

**Comment by NofanTasi** [comment]
@mediaminister  Thanks for kind follow up and expertise! Is this a **known** effect? Of not I would be glad to help filing one. Have a nice day.

**Comment by mediaminister** [comment]
I don't think this is reported earlier by other people and I can't test on CoreELEC. It's very difficult for me to find out what is going wrong. I'll take another look at your debug log.
