### ISSUE TITLE
Unable to add favourites from inside the add-on

### ISSUE THREAD

**Issue by LeetaSehmwa** [add-ons/plugin.video.vrt.nu#891]
### Copypaste  initial report on FB ###
Dank voor de uitnodiging! Even met de deur in huis (niet de exact zelfde fout gevonden op GH, vandaar): programma's toevoegen aan favorieten vanuit de add-on werkt niet. Geen foutmelding, ze kopen gewoon niet bij in de lijst te staan. Op VTRNU zelf favorieten toevoegen werkt wel, en die verschijnen dan ook in de add-on. Enig idee wat hieraan te doen?

### Advice from add-on FB account ###
Report on GH, possible change in source API, similar issues reported for NUPlayer

### To Reproduce ###
1. Go to: any content
2. Click on: long press selected content (~=right click)
3. Scroll down to: select "add to favourites" from dropdown
4. See error: no error, just no effect

### Expected behavior ###
Long press on any content in the add-on results in a dropdown from which to select "add to favourites". Expected behavior would be that said content would thereafter become part of the favourites. 

### Additional context ###
Hardware: NVidia Shield Pro
- Operating system: Android TV 9
- Kodi version: 19.1.0
- Addon version: 2.5.3+matrix.1
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
No error to log from, and still working out how to pull logs on Shield, let me know if you need any.

### Additional observation ###
Favourites added from the VRTNU app or website itself do sync up to the add-on, so the issue is one way only: add-on to source.

**Comment by mediaminister** [comment]
I think there is no issue, there is just some confusion between two different functions:
- **Add to favourites** adds the item to Kodi Favourites menu.
- **Follow** adds the item to VRT NU Add-on My Favorites

I tested and both functions work.

**Comment by LeetaSehmwa** [comment]
I've could see how that would be confusing, though....

Will test later today.

Kind regards / Vriendelijke groet,

Bart Gryp

Sent from mobile / Mobiel verzonden

Personal GMail account

**Comment by LeetaSehmwa** [comment]
Tested in the TV Guide and in All Programs: the "follow" option isn't there to select. Can't seem to add a screenshot using this interface on a phone (the option is there, it just doesn't trigger anything, tried from clipboard, same deal 🤬)
I remember seeing it before, not sure in what context.

**Comment by LeetaSehmwa** [comment]
Update: reinstalled, works! Thanks for clearing that up, OK to close now.
