### ISSUE TITLE
Erratic Playback

### ISSUE THREAD

**Issue by xmnr0x23** [add-ons/plugin.video.vrt.nu#892]
### Describe the bug ###
Erratic playback of some content offered by VRT, something that was introduced several months back. Some (older?) content like "Dwars Door België" is fine but the brand new "Ninja Express" series is totally unwatchable. Might be related to geo-restricted / licensing issues (an oberservation).

More and more shows suffer from this, marring the addon's experience.

### To Reproduce ###
Try playing Ninja Express offered on the VRT nu platform.

### Expected behavior ###
Flawless playback

### Additional context ###
- Operating system: OSMC 2020-11.01 kernel/ Linux 4.9.113-44-osmc
- Kodi version: running Kodi 19.1
- Addon version: 2.5.3+matrix.1
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###

[link to pastebin log](https://pastebin.com/HSWxkc9D)

**Comment by mediaminister** [comment]
Ninja Express is protected with DRM technology. This video stream needs to be decrypted while watching. This consumes CPU power and maybe your hardware is not powerful enough or OSMC/Kodi software components are consuming too much hardware resources. I don't see an error in the VRT NU Add-on and the stream perfectly plays on a x64 Linux system. 

VRT NU offers two stream formats and you can try toggling Widevine DRM in the VRT NU Add-on Playback settings to select the other stream.

**Comment by xmnr0x23** [comment]
Thanks for looking into it. I vaguely remember that I had to install dependencies to get DRM working. This was over a year ago (American series offered by VRT like True Detective S3 needed it), then you guys integrated it somehow?

Back then it worked fine, so I don't think that my Vero 4K has trouble coping?

I'll look into it and try your suggestion.

**Comment by mediaminister** [comment]
> Back then it worked fine, so I don't think that my Vero 4K has trouble coping?

Vero 4K should be fine, I guess it's a software problem then in the newer OSMC versions if an older OSMC version worked fine before.

> I guess I would need remove it and go with an older version?

You currently need an older Widevine CDM. OSMC needs an update to support the newer Widevine CDM.

**Comment by xmnr0x23** [comment]
Yes, older version works fine. Thanks for the tips! Much appreciated.
