### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by jgcoppens** [add-ons/plugin.video.vrt.nu#897]
### Describe the bug ###
When logging in with a newly created VRT NU account, I receive the error: HTTP Error 404 https://toke.vrt.be Unauthorised. Tried logging out and back in into VRT NU on multiple other devices (browsers, iPhone App) which doesn't solve the add-on issue in Kodi.

### To Reproduce ###
1. Go to add-on instellingen
2. Enter username and password and press OK
3. See error

### Additional context ###

- Operating system: Google Chromecast 2020 with Google TV
- Kodi version: 19.1
- Addon version:2.5.3
- Using a VPN: no
- Country you are using the addon from: Belgium

**Comment by mediaminister** [comment]
I'll take a look. On Kodi 18 it seems to work.

**Comment by mediaminister** [comment]
Please test:
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.3-login-2204bb7.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/6854179/plugin.video.vrt.nu-2.5.3-login-2204bb7.zip)
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.3+matrix.1-login-2204bb7.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/6854180/plugin.video.vrt.nu-2.5.3%2Bmatrix.1-login-2204bb7.zip)

**Comment by jgcoppens** [comment]
Tried Kodi 19 Matrix: plugin.video.vrt.nu-2.5.3+matrix.1-login-2204bb7.zip and FIXED. Thanks!

**Comment by mediaminister** [comment]
Thanks for confirming. I'll make a new release.
