### ISSUE TITLE
No live stream, no VOD 

### ISSUE THREAD

**Issue by Rvhalewyn** [add-ons/plugin.video.vrt.nu#906]
### Describe the bug ###

'no connection' error

### To Reproduce ###
1. Go to ...vrt add-on 
2. Click on ....any program in the list 
3. Scroll down to ....
4. See error no connexriin

### Expected behavior ###

Prigralvolaying

### Additional context ###

- Operating system: Libreelec 
- Kodi version: 18.9
- Addon version: 2.5.4
- Using a VPN: no
- Country you are using the addon from: Belgium 

### Log (if available) ###
```paste below
https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0

```

**Comment by frankdpGH** [comment]
Looks like vrtnu-api server is not responding?
2021-09-09 22:45:48.052 T:4325    FATAL <general>: [plugin.video.vrt.nu] URLError: [Errno 7] No address associated with hostname
                                                   url: https://vrtnu-api.vrt.be/search?i=video&size=1&facets[whatsonId]=1032154573527
I can start liveTV from EPG.
Vrtnu app on android is working normally.

**Comment by Rvhalewyn** [comment]
No live VRT from epg here. Epg connected to the add-on through IPTV Manager.

**Comment by mediaminister** [comment]
Fixed in https://github.com/add-ons/plugin.video.vrt.nu/pull/902

Please [upgrade to version v2.5.5](https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.5) manually or wait a couple of days to get the update trough Kodi repo.

**Comment by Rvhalewyn** [comment]
Thanks, VOD working correctly now.
But still no live TV.

**Comment by mediaminister** [comment]
Your Libreelec version needs to support Widevine to get livestreams in the VRT NU Add-on.

**Comment by mediaminister** [comment]
Live TV just works. If not, please provide a debug log.

**Comment by Rvhalewyn** [comment]
Seems to be a Widevine issue after all (see log).

https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0

Which Widevine version should I use? 
Somewhere I read that the newest version doesn't work with Libreelec 9.2.5. And my Eminent 7680 doesn't provide any upgrades. Would that mean I can forget all about watching live programs on that box?

**Comment by mediaminister** [comment]
Widevine doesn't work anymore on Libreelec 9.2.5 since the beginning of September, because Google deprecated all old versions.
You need the newest Widevine version and this only works with LibreELEC 9.2.8 and higher.
