### ISSUE TITLE
Vrt.nu favorites not being synced in kodi addon

### ISSUE THREAD

**Issue by heinreyn** [add-ons/plugin.video.vrt.nu#912]
In the kodi addon there is a "my programs" section that contains a list of a few (previously) liked shows, but it is not the same list as on the vrt.nu site or in the official apps. When I add or remove a show to/from the favorites, it is not synced in the kodi addon list.
In the addon settings, there is an option to manage the "my favorites", but there I can't seem to add or remove shows; only select them to show them in the list of favorites.

### Additional context ###
- Operating system: Nvidia shield TV, as well as chromecast with google tv
- Kodi version: latest on android
- Addon version: latest
- Using a VPN: no
- Country you are using the addon from: BEL

**Comment by SabbeRubbish** [comment]
Same here on Raspberry Pi 2, OSMC (Raspbian)
Have seen this behaviour for a few months now.
Latest Kodi and latest addon.

**Comment by SabbeRubbish** [comment]
After some investigation it seems that it's VRT.nu's API that is the issue.
When calling **https://video-user-data.vrt.be/favorites**, not all favorite shows are returned.
Some old ones are there, but new ones don't seem to get to that list.
Too bad we have such bad documented API's :-(

**Comment by SabbeRubbish** [comment]
I tried to capture traffic from vrt.nu when getting favorites, but the web client doesn't offer a list of your favorites.
The mobile app does however, but it uses HSTS so I couldn't use Fiddler or Charles to decrypt the traffic as the vrt.nu app stopped working when using them as a proxy.

**Comment by michaelarnauts** [comment]
> I tried to capture traffic from vrt.nu when getting favorites, but the web client doesn't offer a list of your favorites. The mobile app does however, but it uses HSTS so I couldn't use Fiddler or Charles to decrypt the traffic as the vrt.nu app stopped working when using them as a proxy.

I recently found out about this tool to automatically patch an APK so it can run in Android 7.0+, and I've used it with mitmproxy: https://github.com/shroudedcode/apk-mitm#allowing-specific-certificates

I've used this on the VTM Go app and worked fine there, so I guess this can also work for the VRT Nu app. You can even use Android Studio and start an emulator from there, even and Android TV version. This allows to quite easy reverse engineer the communication.

**Comment by SabbeRubbish** [comment]
Thank you Michaël! Started up the Android Emulator, patched the APK and launched Fiddler tracing and found the GraphQL Query!
This is the Query to be sent:
POST https://www.vrt.be/vrtnu-api/graphql/v1
`
{
	"operationName": "FavoritesPage",
	"variables": {
		"pageSize": 25,
		"after": null
	},
	"query": "query FavoritesPage($pageSize: Int, $after: ID) {\n  page(id: \"custom:vrtnu-favoritePrograms\") {\n    ... on FavoritesPage {\n      title\n      components {\n        ... on PaginatedTileList {\n          __typename\n          listId\n          displayType\n          title\n          paginatedItems(first: $pageSize, after: $after) {\n            pageInfo {\n              hasNextPage\n              startCursor\n              endCursor\n              __typename\n            }\n            edges {\n              cursor\n              node {\n                __typename\n                ... on ProgramTile {\n                  id\n                  title\n                  image {\n                    objectId\n                    templateUrl\n                    __typename\n                  }\n                  available\n                  program {\n                    favorite\n                    favoriteAction {\n                      id\n                      title\n                      __typename\n                    }\n                    __typename\n                  }\n                  __typename\n                }\n              }\n              __typename\n            }\n            __typename\n          }\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"
}
`

or nicely formatted:
```
{
	"operationName": "FavoritesPage",
	"variables": {
		"pageSize": 25,
		"after": null
	},
	"query": "query FavoritesPage($pageSize: Int, $after: ID) {
  page(id: "custom:vrtnu-favoritePrograms") {
    ... on FavoritesPage {
      title
      components {
        ... on PaginatedTileList {
          __typename
          listId
          displayType
          title
          paginatedItems(first: $pageSize, after: $after) {
            pageInfo {
              hasNextPage
              startCursor
              endCursor
              __typename
            }
            edges {
              cursor
              node {
                __typename
                ... on ProgramTile {
                  id
                  title
                  image {
                    objectId
                    templateUrl
                    __typename
                  }
                  available
                  program {
                    favorite
                    favoriteAction {
                      id
                      title
                      __typename
                    }
                    __typename
                  }
                  __typename
                }
              }
              __typename
            }
            __typename
          }
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
"
}
```
That's a pretty dirty query :-)
Anyway, the problem is also that the shows IDs are being returned, not the programNames as the vrt.nu Kodi plugin uses:

```
{
	"data": {
		"page": {
			"title": "Mijn favorieten pagina",
			"components": [
				{
					"__typename": "PaginatedTileList",
					"listId": "virtual:lists@vrtnu-favoritePrograms",
					"displayType": "stacked",
					"title": "Mijn Lijst",
					"paginatedItems": {
						"pageInfo": {
							"hasNextPage": false,
							"startCursor": "1623487464946",
							"endCursor": "1585217889872",
							"__typename": "PageInfo"
						},
						"edges": [
							{
								"cursor": "1623487464946",
								"node": {
									"__typename": "ProgramTile",
									"id": "1623487464946",
									"title": "Onder vuur",
									"image": {
										"objectId": "wcHMX77930827JnfKh3dJ7wOKP0=",
										"templateUrl": "https://images.vrt.be/orig/2021/08/24/d285eaa0-0510-11ec-b07d-02b7b76bf47f.jpg",
										"__typename": "Image"
									},
									"available": true,
									"program": {
										"favorite": true,
										"favoriteAction": {
											"id": "1623487464946",
											"title": "Onder vuur",
											"__typename": "FavoriteAction"
										},
										"__typename": "Program"
									}
								},
								"__typename": "TileEdge"
							},
						],
						"__typename": "TileConnection"
					}
				}
			],
			"__typename": "FavoritesPage"
		}
	}
}
```

In any case, this IS the right list that we want, but we actually needed the "onder-vuur" programName, and lots of querying to get it out of the query correctly :-)

**Comment by SabbeRubbish** [comment]
If I compare this to the tvshows variable that is used in function `__map_tvshows` in `apihelper.py:228`, this is the related entry:
```
{
 'alternativeImage': '//images.vrt.be/orig/2021/08/24/d285eaa0-0510-11ec-b07d-02b7b76bf47f.jpg',
 'brands': ['een'],
 'description': "'Onder vuur' is een spannende dramareeks over een groep "
                'brandweermannen en -vrouwen die vechten voor het voortbestaan '
                'van hun kazerne in Oostende.\r',
 'episode_count': 15,
 'programName': 'onder-vuur',
 'programUrl': '//www.vrt.be/vrtnu/a-z/onder-vuur/',
 'programWhatsonId': '1024595061527',
 'score': 4.593133,
 'targetUrl': '//www.vrt.be/vrtnu/a-z/onder-vuur.relevant/',
 'thumbnail': '//images.vrt.be/orig/2021/09/18/10b8b4d8-1860-11ec-b07d-02b7b76bf47f.jpg',
 'title': 'Onder vuur',
 'type': 'program'
}
```
The **only** field I think we can use is `title`. No slugs like `onder-vuur` are available and the ids don't match.

**Comment by SabbeRubbish** [comment]
An extra issue is the authentication.
The GraphQL API hasn't been used yet by this add-on, and there are only 2 access tokens available: 
- VRT Login: used for using the search API at `https://search.vrt.be/*`
- X-VRT_TOKEN: used for connecting to the current favorites API at `https://video-user-data.vrt.be/favorites`

We would need to get all needed tokens for the GraphQL API at `https://www.vrt.be/vrtnu-api/graphql/v1`

**Comment by SabbeRubbish** [comment]
So in short: these are the tasks to be completed:

- [ ] Get a GraphQL Token
- [ ] Change the code in `favorites.py:32` function `refresh` to use the GraphQL token
- [ ] Change the code in `favorites.py:32` function `refresh` to use the GraphQL endpoint
- [ ] Add a function `titles` to `favorites.py` returning the titles instead of the `programName`s of the favorite shows
- [ ] Change the statement in `apihelper.py:223` to get the show titles
- [ ] Add a statement after `apihelper.py:229` to get the show titles
- [ ] Change the statement in `apihelper.py:231` to filter on title rather than programName

That should cover most of it.

**Comment by SabbeRubbish** [comment]
Ok, dived deeper into the authentication.
The GraphQL endpoint also accepts the VRT login access token `vrtlogin-at`.
That's good news, we don't have to get an additional token then!

**Comment by SabbeRubbish** [comment]
Interesting point I came about in `favorites.py:89`:
```
# NOTE: Updates to favorites take a longer time to take effect, so we keep our own cache and use it
```
This means that when setting a program as favorite in Kodi, it doesn't push it to VRT.nu by default (or may even fail to) but DOES keep it locally, making you *think* it was added to the list.
Interesting to know that when testing.

**Comment by SabbeRubbish** [comment]
An extra problem I found is the cache.
The cache is used directly from the API call in business logic.
That's bad design :) and is giving me a headache now as the API result needs to be transformed in order to use it (the GraphQL response is VERY different from the Search API response).

**Comment by SabbeRubbish** [comment]
I can confirm this also works on my Raspberry Pi 2 running latest version of Kodi/addon incl. the above commit.
