### ISSUE TITLE
Resume points no longer sent to vrt nu?

### ISSUE THREAD

**Issue by maanwater** [add-ons/plugin.video.vrt.nu#914]
### Describe the bug ###
Since recently, resume points no longer seem to be sent to VRT NU (not on pause nor at the end). As a result, my watching history is not reflected on the VRT NU website/app. 

### To Reproduce ###
1. Start watch an episode in the kodi app
2. Pause the episode in the middle
3. Navigate to the VRT NU website
4. The just watched episode is not in the Verder Kijken swimlane on the homepage nor can you continue watching where you left off in kodi when navigating to the episode page

### Expected behavior ###
I would expect a resumepoint to be sent to VRT NU on pause and at the end of an episode.

**Comment by mediaminister** [comment]
VRT changed API endpoints. I made a fix.

Can you please test the following zip package and report if it works well.
- Fix for Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.5+matrix.1-resumepoints-96d48f4.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/7253912/plugin.video.vrt.nu-2.5.5%2Bmatrix.1-resumepoints-96d48f4.zip)
- Fix for Kodi 18 Leia: [plugin.video.vrt.nu-2.5.5-resumepoints-96d48f4.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/7253913/plugin.video.vrt.nu-2.5.5-resumepoints-96d48f4.zip)

**Comment by maanwater** [comment]
I tested the Kodi 18 version (removed my current version and installed the zip), but it still does not seem to work. Should I see the resume points call in the logs? Because I don't see anything there.

**Comment by mediaminister** [comment]
You need to enable debug loggin to see all network calls: https://kodi.wiki/view/Log_file/Easy

**Comment by maanwater** [comment]
> But I see why it doesn't work very well. The VRT NU Website uses the webbrowser cache which can't be influenced from the Kodi app.

Do you mean that it will not work to send resumepoints from kodi?

**Comment by mediaminister** [comment]
It works, but not in realtime.
