### ISSUE TITLE
"There is a problem connecting with the Internet" error over and over again

### ISSUE THREAD

**Issue by KaiNickson** [add-ons/plugin.video.vrt.nu#918]
Error pops up as soon as I open the program list and keeps popping up. Sometimes I have to force close the kodi app to make the pop-up's stop.
As a result I can't watch anything through the add-on
It looks similar to the issue described in [#907](https://github.com/add-ons/plugin.video.vrt.nu/issues/907)
However I run 2.5.5 from the Kodi repositories on Kodi 19.3 for Android TV.

I tried different credentials, reinstalling the add-on, turned widevine off, resetting the add-on config, ...
Nothing made the issue change it's behavior.

Internet connection goes via proxy, other add-ons can stream just fine (ie. GoPlay)

Location: Belgium

In the logs i get the following messages:

> 2021-12-14 00:31:08.271 T:11730    INFO <general>: initializing python engine.
> 2021-12-14 00:31:09.120 T:11730   FATAL <general>: [plugin.video.vrt.nu] URL https://www.vrt.be/vrtnu-static/screenshots/een.jpg not found in texture cache
> 2021-12-14 00:31:09.462 T:11730   FATAL <general>: [plugin.video.vrt.nu] URL https://www.vrt.be/vrtnu-static/screenshots/canvas.jpg not found in texture cache
> 2021-12-14 00:31:10.059 T:11730   FATAL <general>: [plugin.video.vrt.nu] URL https://www.vrt.be/vrtnu-static/screenshots/ketnet.jpg not found in texture cache
> 2021-12-14 00:31:11.019 T:11730    INFO <general>: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
> 2021-12-14 00:31:11.081 T:10999   ERROR <general>: CTextureBundleXBT: failed to decompress frame with 3207 unpacked bytes to 70196 bytes
> 2021-12-14 00:31:11.081 T:11692   ERROR <general>: CTextureBundleXBT: failed to decompress frame with 3408 unpacked bytes to 70196 bytes
> 2021-12-14 00:31:11.081 T:10999   ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/Ketnet.png
> 2021-12-14 00:31:11.081 T:11692   ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/Canvas.png
> 2021-12-14 00:31:14.099 T:11730    INFO <general>: initializing python engine.
> 2021-12-14 00:31:15.263 T:11730   FATAL <general>: [plugin.video.vrt.nu] hls_aes is not available for this stream, please try toggling the "Use Widevine DRM" setting
> 2021-12-14 00:31:17.936 T:11730    INFO <general>: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
> 2021-12-14 00:31:17.958 T:10965   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vrt.nu/play/id/vualto_canvas_geo]
> 2021-12-14 00:31:46.748 T:11730    INFO <general>: initializing python engine.
> 2021-12-14 00:31:48.125 T:11730   FATAL <general>: [plugin.video.vrt.nu] URL https://www.vrt.be/vrtnu-static/screenshots/ketnet.jpg not found in texture cache
> 2021-12-14 00:31:49.089 T:11730    INFO <general>: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
> 2021-12-14 00:31:51.391 T:11730    INFO <general>: initializing python engine.
> 2021-12-14 00:31:52.081 T:10965    INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.vrt.nu/play/id/vualto_canvas_geo
> 2021-12-14 00:31:52.087 T:11846    INFO <general>: Creating InputStream
> 2021-12-14 00:31:52.148 T:11730    INFO <general>: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
> 2021-12-14 00:31:52.189 T:11846    INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1920 x 1080)
> 2021-12-14 00:31:52.202 T:11846   ERROR <general>: GetDirectory - Error getting /data/user/0/org.xbmc.kodi/cache/apk/assets/addons/inputstream.adaptive/
> 2021-12-14 00:31:52.428 T:11846   ERROR <general>: AddOnLog: inputstream.adaptive: Key system request: com.widevine.alpha
> 2021-12-14 00:31:52.725 T:11846    INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 3, Type: live, Download speed: 0.0000 Bytes/s
> 2021-12-14 00:32:21.244 T:10948    INFO <general>: CPeripheralBusAndroid: input device "SONY TV RC MIC 001" with ID 939 removed
> 2021-12-14 00:32:21.244 T:10948    INFO <general>: UnregisterRemovedDevices - device removed from joystick/android/inputdevice/939: SONY TV RC MIC 001 (054C:0BE8)
> 2021-12-14 00:32:23.406 T:11846   ERROR <general>: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
> 2021-12-14 00:32:23.406 T:11846   ERROR <general>: CCurlFile::Open failed with code 0 for https://widevine-license.vudrm.tech/proxy:
>                                                    
> 2021-12-14 00:32:23.406 T:11846   ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
> 2021-12-14 00:32:23.409 T:11846   ERROR <general>: AddOnLog: inputstream.adaptive: Initialize failed (SingleSampleDecrypter)
> 2021-12-14 00:32:23.414 T:11846   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.vrt.nu/play/id/vualto_canvas_geo]
> 2021-12-14 00:32:23.414 T:11846    INFO <general>: CVideoPlayer::OnExit()
> 2021-12-14 00:32:23.424 T:11846    INFO <general>: ADDON: Dll Destroyed - InputStream Adaptive
> 2021-12-14 00:32:23.437 T:11882    INFO <general>: Deleting settings information for files plugin://plugin.video.vrt.nu/play/id/vualto_canvas_geo
> 2021-12-14 00:32:23.460 T:10965    INFO <general>: CVideoPlayer::CloseFile()
> 2021-12-14 00:32:23.462 T:10965    INFO <general>: VideoPlayer: waiting for threads to exit
> 2021-12-14 00:32:23.462 T:10965    INFO <general>: VideoPlayer: finished waiting
> 2021-12-14 00:32:26.766 T:10948 WARNING <general>: CAndroidJoystickState: ignoring unknown axis 32 on input device "SONY TV RC MIC 001" with ID 940
> 2021-12-14 00:32:27.021 T:10948    INFO <general>: Register - new joystick device registered on android->android/inputdevice/940: SONY TV RC MIC 001 (054C:0BE8)
> 2021-12-14 00:32:27.759 T:11730    INFO <general>: initializing python engine.
> 2021-12-14 00:32:27.906 T:11730    INFO <general>: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
> 2021-12-14 00:32:36.822 T:10965    INFO <general>: Samba is idle. Closing the remaining connections
> 2021-12-14 00:32:42.644 T:10965    INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
> 2021-12-14 00:33:21.346 T:11730    INFO <general>: initializing python engine.
> 2021-12-14 00:33:21.528 T:11730    INFO <general>: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
> 2021-12-14 00:33:38.043 T:11730    INFO <general>: initializing python engine.
> 2021-12-14 00:33:38.233 T:11730    INFO <general>: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
> 2021-12-14 00:33:49.136 T:11730    INFO <general>: initializing python engine.
> 2021-12-14 00:33:49.213 T:11730    INFO <general>: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
> 2021-12-14 00:33:53.593 T:11730    INFO <general>: initializing python engine.
> 2021-12-14 00:34:23.471 T:10948    INFO <general>: CPeripheralBusAndroid: input device "SONY TV RC MIC 001" with ID 940 removed
> 2021-12-14 00:34:23.472 T:10948    INFO <general>: UnregisterRemovedDevices - device removed from joystick/android/inputdevice/940: SONY TV RC MIC 001 (054C:0BE8)
> 2021-12-14 00:35:57.512 T:10948 WARNING <general>: CPeripheralBusAndroid: failed to remove input device with ID 925 because it couldn't be found
> 2021-12-14 00:35:57.577 T:10948    INFO <general>: CPeripheralBusAndroid: input device "Logitech Logitech Illuminated Keyboard" with ID 926 removed
> 2021-12-14 00:35:57.577 T:10948    INFO <general>: UnregisterRemovedDevices - device removed from joystick/android/inputdevice/926: Logitech Logitech Illuminated Keyboard (046D:C318)
> 2021-12-14 00:36:27.337 T:10965    INFO <general>: CWinSystemAndroid::DestroyWindow
> 2021-12-14 00:36:27.395 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:36:30.670 T:10948 WARNING <general>: Skipped 3 duplicate messages..
> 2021-12-14 00:36:30.670 T:10948 WARNING <general>: CAndroidJoystickState: ignoring unknown axis 32 on input device "Logitech Logitech Illuminated Keyboard" with ID 942
> 2021-12-14 00:36:31.558 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:36:31.581 T:10948    INFO <general>: Register - new joystick device registered on android->android/inputdevice/942: Logitech Logitech Illuminated Keyboard (046D:C318)
> 2021-12-14 00:36:32.650 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:36:35.786 T:10948 WARNING <general>: Skipped 3 duplicate messages..
> 2021-12-14 00:36:35.785 T:10948 WARNING <general>: CAndroidJoystickState: ignoring unknown axis 32 on input device "SONY TV RC MIC 001" with ID 943
> 2021-12-14 00:36:36.297 T:10948    INFO <general>: Register - new joystick device registered on android->android/inputdevice/943: SONY TV RC MIC 001 (054C:0BE8)
> 2021-12-14 00:36:36.531 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:36:47.534 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:36:47.534 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:36:57.972 T:11730   FATAL <general>: Skipped 8 duplicate messages..
> 2021-12-14 00:36:57.972 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:37:08.300 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:37:08.300 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:37:19.231 T:11730   FATAL <general>: Skipped 10 duplicate messages..
> 2021-12-14 00:37:19.231 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:37:27.440 T:10948    INFO <general>: Skipped 7 duplicate messages..
> 2021-12-14 00:37:27.440 T:10948    INFO <general>: CPeripheralBusAndroid: input device "SONY TV RC MIC 001" with ID 943 removed
> 2021-12-14 00:37:27.462 T:10948    INFO <general>: UnregisterRemovedDevices - device removed from joystick/android/inputdevice/943: SONY TV RC MIC 001 (054C:0BE8)
> 2021-12-14 00:37:27.553 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:37:37.691 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:37:37.691 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:37:47.979 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:37:47.979 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:37:57.982 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:37:57.982 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:38:08.860 T:11730   FATAL <general>: Skipped 10 duplicate messages..
> 2021-12-14 00:38:08.860 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:38:18.038 T:10948 WARNING <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:38:18.038 T:10948 WARNING <general>: CAndroidJoystickState: ignoring unknown axis 32 on input device "SONY TV RC MIC 001" with ID 944
> 2021-12-14 00:38:18.459 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:38:18.554 T:10948    INFO <general>: Register - new joystick device registered on android->android/inputdevice/944: SONY TV RC MIC 001 (054C:0BE8)
> 2021-12-14 00:38:19.393 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:38:29.693 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:38:29.693 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:38:40.537 T:11730   FATAL <general>: Skipped 10 duplicate messages..
> 2021-12-14 00:38:40.537 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:38:51.705 T:11730   FATAL <general>: Skipped 10 duplicate messages..
> 2021-12-14 00:38:51.705 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:38:59.498 T:10948    INFO <general>: Skipped 7 duplicate messages..
> 2021-12-14 00:38:59.498 T:10948    INFO <general>: CPeripheralBusAndroid: input device "SONY TV RC MIC 001" with ID 944 removed
> 2021-12-14 00:38:59.499 T:10948    INFO <general>: UnregisterRemovedDevices - device removed from joystick/android/inputdevice/944: SONY TV RC MIC 001 (054C:0BE8)
> 2021-12-14 00:38:59.774 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:39:04.689 T:10948 WARNING <general>: Skipped 5 duplicate messages..
> 2021-12-14 00:39:04.688 T:10948 WARNING <general>: CAndroidJoystickState: ignoring unknown axis 32 on input device "SONY TV RC MIC 001" with ID 945
> 2021-12-14 00:39:05.181 T:10948    INFO <general>: Register - new joystick device registered on android->android/inputdevice/945: SONY TV RC MIC 001 (054C:0BE8)
> 2021-12-14 00:39:05.596 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:39:16.122 T:11730   FATAL <general>: Skipped 10 duplicate messages..
> 2021-12-14 00:39:16.122 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:39:26.314 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:39:26.313 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:39:36.512 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:39:36.512 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:39:46.828 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:39:46.827 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:39:57.361 T:11730   FATAL <general>: Skipped 10 duplicate messages..
> 2021-12-14 00:39:57.361 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:40:07.581 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:40:07.581 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:40:17.745 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:40:17.745 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:40:28.451 T:11730   FATAL <general>: Skipped 10 duplicate messages..
> 2021-12-14 00:40:28.451 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:40:36.673 T:10948    INFO <general>: Skipped 7 duplicate messages..
> 2021-12-14 00:40:36.672 T:10948    INFO <general>: CPeripheralBusAndroid: input device "SONY TV RC MIC 001" with ID 945 removed
> 2021-12-14 00:40:36.678 T:10948    INFO <general>: UnregisterRemovedDevices - device removed from joystick/android/inputdevice/945: SONY TV RC MIC 001 (054C:0BE8)
> 2021-12-14 00:40:36.894 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:40:47.508 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:40:47.507 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:40:57.915 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:40:57.915 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:41:08.623 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:41:08.623 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:41:19.622 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:41:19.621 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:41:30.372 T:11730   FATAL <general>: Skipped 9 duplicate messages..
> 2021-12-14 00:41:30.372 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/
> 2021-12-14 00:41:40.831 T:11730   FATAL <general>: Skipped 8 duplicate messages..
> 2021-12-14 00:41:40.831 T:11730   FATAL <general>: [plugin.video.vrt.nu] URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'token.vrt.be'. (_ssl.c:1123)
>                                                    url: https://token.vrt.be/vrtnuinitlogin?provider=site&destination=https://www.vrt.be/vrtnu/

**Comment by KaiNickson** [comment]
Did some further analysis and arranged a reboot/update of the proxy server.
This seems to have resolved the issue.It is still not clear to me why I only had a problem with this addon.
But the issue seems to be out of scope here.

**Comment by dagwieers** [comment]
Thanks for reporting back with the solution. This helps other users with similar issues.
