### ISSUE TITLE
Requesting Belgian phone number (account already has one)

### ISSUE THREAD

**Issue by tommyhaghighi** [add-ons/plugin.video.vrt.nu#919]
### Describe the bug ###

Trying to watch Het Journaal, worked fine until yesterday. Now it is asking to add a Belgian phone number to the account. I have done this, as well as connecting it to an eID, but the add-on still gives this issue. Can watch fine on the VRT NU website, and have tried uninstalling and reinstalling the addon, updating etc.

This is happening on Firestick, and on Windows 10, in two different houses, two different internet providers.

**Comment by michaelarnauts** [comment]
I think there is a clear tokens item in the advanced settings of the addon, maybe it can help to try this first.

**Comment by tommyhaghighi** [comment]
Hi there, I tried this but it didn't change anything. I am in the UK by the way. It works fine if I use a Belgian VPN, but until a few days ago I could use it without with no issue. I can still watch it on their website with no VPN.

**Comment by mediaminister** [comment]
VRT changed their stream api url.
Please clear VRT tokens and test this package: 
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.5-streamservice-d734f98.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/7740568/plugin.video.vrt.nu-2.5.5-streamservice-d734f98.zip)

Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.5+matrix.1-streamservice-d734f98.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/7740567/plugin.video.vrt.nu-2.5.5%2Bmatrix.1-streamservice-d734f98.zip)
