### ISSUE TITLE
VrtNu streaming problem

### ISSUE THREAD

**Issue by azertyfred** [add-ons/plugin.video.vrt.nu#933]
Hi, I'm using VrtNu add-on in Kodi on Raspberry Pi 3 for some years now. Recently playback fails: it works for some time (30 sec), but then stream starts to falter and a circle appear with percentages, the video can't play fluently anymore. 

I've been through the discussions/proposed solution of inputstream adaptive, widevine, reinstalled Widevine because I first thought it was related to widevine (VTMGo has the same problem, the Arte add-on hasn't) but nothing has helped. 

I recently changed my Proximus internet subscription from start to unlimited so the speed of my internet is even faster now, but still.. 

Also I verified by installing Kodi on my laptop (Linux Mint) where it works flawlessly and reinstalled Kodi on Raspberry Pi with a 'new' VrtNu add-on with fresh settings but hasn't helped either (I replaced a backup afterwards). 

Anyone has a clue why the stream doesn't seem to buffer correctly?

Thks

- Operating system: LibreELEC 9.2.8 (kernel version Linux 4.19.127)
- Kodi version: 18.9
- Addon version: 2.5.6
- Using a VPN: no
- Country you are using the addon from:  Belgium

**Comment by peno64** [comment]
The problem is related to the latest widevine cdm library. Restoring a backup to a previous version of widevine cdm solves the problem.

**Comment by mediaminister** [comment]
This is indeed a problem with Widevine CDM and the InputStream Adaptive plugin.
The problem is reported at https://github.com/xbmc/inputstream.adaptive/issues/877

**Comment by mbsaerens** [comment]
Same issue with a raspberry pi 2.
Is there a work-around? Can we use an older version of the VrtNu streaming add-on?

**Comment by mbsaerens** [comment]
Same issue with Raspberry Pi 2

Does the VrtNu add-on work with an older version of widevine? Can we use an older version of the VrtNu add-on? If so, is there a guide somewhere?

**Comment by peno64** [comment]
It works with an older version of widevine. Older version of vrt nu addon? I don't know. I guess not.
To install an older version of widevine, in kodi goto Add-Ons, My add-ons, All,  InputStream Helper, Configure, Restore Widevine CDB library and choose a previous version. After that, restart the pi

**Comment by mbsaerens** [comment]
@peno64 Thanks for the help! I already reinstalled LibreElec completely. My backup Widevine is lost because of this. Any other suggestions?

**Comment by peno64** [comment]
@mbsaerens 
Can you navigate to \\<ip>\Userdata\addon_data\script.module.inputstreamhelper ?
There should be a folder backup there. You can copy the files from a backup there (I hope you have a backup of your sd card).
If you don't have a backup, I can provide the files from my PI.

**Comment by peno64** [comment]
I ment \\ip\Userdata\addon_data\script.module.inputstreamhelper where ip is the  ip of the pi. For example 192.168.1.120

**Comment by mbsaerens** [comment]
@peno64 
No backup found. I would be surprised if there was one, since I cleared the SD card and installed LibreELEC from scratch.
`
LibreELEC:~/.kodi/addons/script.module.inputstreamhelper # ls -l
total 22
-rw-r--r--    1 root     root          1075 Jan 25 21:34 LICENSE.txt
-rw-r--r--    1 root     root         11957 Jan 25 21:34 README.md
-rw-r--r--    1 root     root          4151 Jan 25 21:34 addon.xml
-rw-r--r--    1 root     root           229 Jan 25 21:34 default.py
drwxr-xr-x    3 root     root          1024 Jan 25 22:47 lib
drwxr-xr-x    3 root     root          1024 Jan 25 21:34 resources
`

A copy of your files will be appreciated. Replacing the libwidevinecdm.so in ~/.kodi/cdm by a version i found in a random Chrome OS Recovery Image did not work well.

**Comment by dagwieers** [comment]
This issue is indeed very problematic for new users, but also for the non-technical user that suddenly is getting a newer CDM 😞

**Comment by peno64** [comment]
@mbsaerens 
See https://drive.google.com/drive/folders/1rUKXlS_fZmIrT74wRh07cmvqV7emgWT0

**Comment by jefke-glider** [comment]
same problem here on a raspberry4. Reinstalled it with LibreElec10.0.1. At first everything seemed to work. Then one program asked for Widevine CDM, installed it, and after that, the stuttering started....

**Comment by mbsaerens** [comment]
@peno64 Thank you! Much appreciated.

The location of the inputstreamerhelper was at a different location on my device: /storage/.kodi/addons/script.module.inputstreamhelper
After putting the backup folder there and a reboot, the plugin still couldn't find the backups.

For other people having this issue, The SlyGuy Common service add-on has now been updated and offered a solution for me.
In case you need to install the SlyGuy Common service add-on, it is explained [here](https://www.matthuisman.nz/2020/02/slyguy-kodi-repository.html)
In kodi goto Add-Ons, My add-ons, All, SlyGuy Common
Click Configure
On the left, lick Advanced and click (Re)install Widevine CDM. In the popup, select 4.10.2252.0

**Comment by azertyfred** [comment]
restoring a previous version of Widevine (4.10.2252.0) seems to fix the problem (for now). I had to use the workaround with the SlyGuy common service add-on because restoring a previous version in the 'normal' way didn't work (I already tried to reinstall Widevine earlier, maybe that's the reason?). Anyway, thks a lot for your help to all of you, I hope it will stay like this :)

**Comment by dagwieers** [comment]
We need to add the option to install an older Widevine version from the Internet. There is however a technical problem to do that for ARM (the most popular platform), and that is why it hasn't been done.

**Comment by peno64** [comment]
@dagwieers 
What do you mean with that there is a technical problem on ARM?
As explained by azertyfred, SlyGuy has in  its common addon an option to do that.I tried  it and it seems to work ok. This is my PI4 under the latest libreelec. It only says that the OS doesn't support this widevine version yet, but it allows to install it and it seems to work ok (tried with vtm go playing a movie).

**Comment by michaelarnauts** [comment]
Slyguy has a location where he hosts the extracted windevine binaries, but this isn't allowed due to the Widevine redistribution license. Not really an issue for a 3th party add-on that isn't in the Kodi repo, but as soon as you want to do include your add-on in the repo, there are some rules you need to follow.

This is why Inputstream helper downloads the chromeos images from the Google servers and extracts it from that image.

**Comment by peno64** [comment]
@michaelarnauts 
Sounds like a very logical explanation. 
Thx

**Comment by kverkind** [comment]
Problem exist on Nvidia shield. Slyguy gives me no option to restore older version. Any idea?

**Comment by peno64** [comment]
@kverkind 
For android, widevine is part of the OS (or maybe it is the chrome browser) and as such comes with updates of android. As such, I don't think it is possible in android to let the user choose the version.

**Comment by kverkind** [comment]
> @kverkind For android, widevine is part of the OS (or maybe it is the chrome browser) and as such comes with updates of android. As such, I don't think it is possible in android to let the user choose the version.

What is the solution in that case?

**Comment by peno64** [comment]
I have no idea. It's the first time I hear that the problem also occurs on other devices than raspberry  pi.

**Comment by wimpunk** [comment]
On my raspberry 3 with libreelec I got the timer very much.  Did the next steps:

- used SlyGuy to downgrade widewine, didn't helped to play "het journaal" in a decent way
- rebooted, didn't helped
- disabled Inputstream Adaptive, didn't helped, couldn't even start playing
- enabled Inputstream Adaptive, worked.

Not sure if it helps anyone, at least it helped me. Only thing left to do is add cooling to my raspberry.

**Comment by Jefken** [comment]
> @peno64 Thank you! Much appreciated.
> 
> The location of the inputstreamerhelper was at a different location on my device: /storage/.kodi/addons/script.module.inputstreamhelper After putting the backup folder there and a reboot, the plugin still couldn't find the backups.
> 
> For other people having this issue, The SlyGuy Common service add-on has now been updated and offered a solution for me. In case you need to install the SlyGuy Common service add-on, it is explained [here](https://www.matthuisman.nz/2020/02/slyguy-kodi-repository.html) In kodi goto Add-Ons, My add-ons, All, SlyGuy Common Click Configure On the left, lick Advanced and click (Re)install Widevine CDM. In the popup, select 4.10.2252.0

This works as well for amlogic devices. Thanks!

**Comment by kverkind** [comment]
Is this a bug in Widevine or in this package?

**Comment by peno64** [comment]
It's a result of a change in widevine. It does also appears with other addons.

**Comment by mediaminister** [comment]
> Is this a bug in Widevine or in this package?

It's a feature, some kind of nasty game. Widevine has changed something without publishing the details. The open-source community has to guess how to fix this.
Someday watching content encrypted with proprietary Widevine DRM will fail on open-source systems like Kodi.

**Comment by Jefken** [comment]
Hopefully, someone finds a replacement for this feature, this would make us independent from "Google" I assume.

**Comment by mediaminister** [comment]
There was an open-source implemantation available: HLS AES encryption.
But last summer VRT removed this stream: https://www.vrt.be/heb-je-een-vraag/s/article/Waarom-werkt-sinds-19-juli-2021-de-stream-van-de-VRT-niet-meer-op-mijn-toestel

**Comment by pwauters** [comment]
Thank you so much for sharing the information about a broken Widevine! It took me a couple of frustrating days to find out that was the root cause of all my recent issues. The SlyGuy trick did the job for me. No more live streaming issues.

**Comment by Bart80-1** [comment]
I found an interesting comment: https://github.com/xbmc/inputstream.adaptive/issues/877#issuecomment-1114117848
Seems like a newer version of Widevine has fixed this issue?
Can anybody confirm/deny that updating to the latest Widevine now solves the issue? 
Would be great as otherwise, the lack of a recent Widevine that works seems like a timebomb underneath the Kodi/Plugins fun...

**Comment by peno64** [comment]
How do you conclude that it  is fixed? The last comment  is that reverting widevine fixes the problem. Just like we also have to do for vrt nu. Reverting means install a previous version...

**Comment by Bart80-1** [comment]
> How do you conclude that it is fixed? The last comment is that reverting widevine fixes the problem. Just like we also have to do for vrt nu. Reverting means install a previous version...

I don't conclude anything ;) I am just referring to a comment in an issue that is identified earlier in this thread as the root cause of this thread's issue. Best case, no reverting to earlier versions of Widevine are required anymore; worst case, nothing happened. Worth a check I guess ;)

**Comment by Bart80-1** [comment]
> > How do you conclude that it is fixed? The last comment is that reverting widevine fixes the problem. Just like we also have to do for vrt nu. Reverting means install a previous version...
> 
> I don't conclude anything ;) I am just referring to a comment in an issue that is identified earlier in this thread as the root cause of this thread's issue. Best case, no reverting to earlier versions of Widevine are required anymore; worst case, nothing happened. Worth a check I guess ;)

Meanwhile I installed Widevine 4.10.2449.0 . I looked at some VOD content (2 or 3 episodes meanwhile) which seemed to work nicely. At this moment I get errors but I guess they are related to https://github.com/add-ons/plugin.video.vrt.nu/issues/975 .

Could be interesting to check out further and communicate? It would mean that this issue is fixed (I hope it stays that way ;) ).

**Comment by mediaminister** [comment]
Since there are newer versions of Widevine CDM released that are working, I consider this as fixed.
