### ISSUE TITLE
Stream video is garbled

### ISSUE THREAD

**Issue by TASSDevon** [add-ons/plugin.video.vrt.nu#940]
Play any vrtnu video, I'm playing for example Het Journaal, the audio is OK but the video looks like this: https://imgur.com/a/DDVq0gy

Any ideas? Last week somewhere it started to be like this.

**Comment by mediaminister** [comment]
I guess you should check your hardware or Widevine CDM version in InputStreamHelper.

**Comment by mediaminister** [comment]
I'm closing this, cause this is definitely not a VRT NU Add-on problem.
