### ISSUE TITLE
Live channels Eén and Canvas are not playing

### ISSUE THREAD

**Issue by jcjdammers** [add-ons/plugin.video.vrt.nu#944]
Hi,
Live channels "Eén" and "Canvas" are not playing for me, and display the "Oeps, er ging iets mis, ...." error message on the screen.
I have a VRT NU account with a verified phone number. Watching the channels in the VRT NU web site on my laptop with a web browser works fine.
I use LE v10.0.2 with Kodi v19.4 and the addon v2.5.7+matrix.1.
I have uploaded my Kodi.log to [https://paste.kodi.tv/bukiyayado](https://paste.kodi.tv/bukiyayado)
Hope you can help me, thanks,
Jeroen.

See also the Input Stream Helper Info:

![InputStreamHelperInfo](https://user-images.githubusercontent.com/10573570/163242201-8cc3d5eb-65bc-4546-9a68-6906a4f4d306.jpg)

**Comment by mediaminister** [comment]
Thanks for reporting.
I found a problem with the authentication when watching from abroad.
I'll look into this.

**Comment by jcjdammers** [comment]
Yes the fix works fine.
Many thanks.

**Comment by mediaminister** [comment]
Thanks for conforming, I'll do a new release.
