### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by dvdh80** [add-ons/plugin.video.vrt.nu#953]
I can watch VRT NU in the browser and the VRT app, but not in Kodi. I tried Kodi 18.9 & 19.1 with addon 2.5.5(+) and 2.5.7(+). I always get the message 'connection problem - network/isp/VRT NU'

**Comment by mediaminister** [comment]
You should use the latest version 2.5.9

**Comment by dvdh80** [comment]
Ok thanks, it didn't show up in the auto-update. It works now.

**Comment by dvdh80** [comment]
I have a box with Android 7 and a box with Android 9, but on the 9 I can't view all videos with Kodi 19.x, especially the documentaries... Only 18.x plays all videos on my Android 9 box (no matter which addon)

**Comment by mediaminister** [comment]
Please provide a debug log if this problem is not fixed in add-on version v2.5.10: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.10

**Comment by mediaminister** [comment]
Closing this, as there is a new issue to discuss the problem with playing Widevine DRM protected documentaries.
