### ISSUE TITLE
Problem with access via TV guide

### ISSUE THREAD

**Issue by ldebt** [add-ons/plugin.video.vrt.nu#954]
Can not start a program via TV guide. Always get the message "HTTP Error 400    
https://search7.vrt.be/search?i=video&size=1&facets[whatsonId]=
Bad Request" Same problem on Samsung SM-T580 Tablet and Bqeel Y5 mediaplayer.
Program does start using other option like Search VRT NU iso. TV guide.

**Comment by ldebt** [comment]
Open KODI - Go to VRT NU - Select TV guide - Select date - Select channel - Select program >> HTTP Error 400 - Push OK >> Playback failed

**Comment by mediaminister** [comment]
This problem should be fixed in add-on version 2.5.10: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.10

**Comment by ldebt** [comment]
New version manually installed. Problem no longer occurs. Thank you for the excellent assistance.
