### ISSUE TITLE
Playing from EPG (IPTV Manager)

### ISSUE THREAD

**Issue by frankdpGH** [add-ons/plugin.video.vrt.nu#967]
Hi,
 Thanks for fixing "Fix playing from tv guide #956"
Please have a look too when starting the program from EPG with IPTV Manager : same error.
Log attached.

### To Reproduce ###
1. Go to EPG.
2. Click on Selected program
3. Choose "Play Program".
4. Same error as #956 / #954

### Expected behavior ###
Selected tv show should be playing

### Additional context ###
See log file
- Windows or others
- Kodi version 19.4 matrix
- Addon version 2.5.10
- Using a VPN: no
- Country you are using the addon from: BE

### Log  ###
[kodi.log](https://github.com/add-ons/plugin.video.vrt.nu/files/8598900/kodi.log)

**Comment by mediaminister** [comment]
Please try this fix and report if it works.
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.10-iptvmanager-35c8bf0.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8599259/plugin.video.vrt.nu-2.5.10-iptvmanager-35c8bf0.zip)
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.10+matrix.1-iptvmanager-35c8bf0.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8599260/plugin.video.vrt.nu-2.5.10%2Bmatrix.1-iptvmanager-35c8bf0.zip)

**Comment by frankdpGH** [comment]
> Please try this fix and report if it works. Kodi 18 Leia: [plugin.video.vrt.nu-2.5.10-iptvmanager-35c8bf0.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8599259/plugin.video.vrt.nu-2.5.10-iptvmanager-35c8bf0.zip) Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.10+matrix.1-iptvmanager-35c8bf0.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8599260/plugin.video.vrt.nu-2.5.10%2Bmatrix.1-iptvmanager-35c8bf0.zip)

Thanks! problem is solved with this version. First a refresh of IPTV manager was needed.
Could install it on a Andoid TV armV7 . On Windows installation failed.
