### ISSUE TITLE
"Most Recent" Error

### ISSUE THREAD

**Issue by frankdpGH** [add-ons/plugin.video.vrt.nu#969]
Hi,
Can you please have a look at the "Most Recent" view , it ends with error on my different Kodis
Log attached.

To Reproduce

Go to VRT Nu main menu.
Click on "Most Recent" and get error.

Additional context
    return add_https_proto(url.replace('images.vrt.be/orig', 'images.vrt.be/w1920hx'))
     AttributeError: 'NoneType' object has no attribute 'replace'

See log file

Windows/Android
Kodi version 19.4 matrix
Addon version 2.5.10
Using a VPN: no
Country you are using the addon from: BE

Log
[kodi2.log](https://github.com/add-ons/plugin.video.vrt.nu/files/8599445/kodi2.log)

**Comment by mediaminister** [comment]
I have a fix, please test:
Kodi 18 Leia: [plugin.video.vrt.nu-2.5.10-recent-282296f.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8599601/plugin.video.vrt.nu-2.5.10-recent-282296f.zip)
Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.10+matrix.1-recent-282296f.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8599599/plugin.video.vrt.nu-2.5.10%2Bmatrix.1-recent-282296f.zip)

**Comment by frankdpGH** [comment]
> I have a fix, please test: Kodi 18 Leia: [plugin.video.vrt.nu-2.5.10-recent-282296f.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8599601/plugin.video.vrt.nu-2.5.10-recent-282296f.zip) Kodi 19 Matrix: [plugin.video.vrt.nu-2.5.10+matrix.1-recent-282296f.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8599599/plugin.video.vrt.nu-2.5.10%2Bmatrix.1-recent-282296f.zip)

All working now (on matrix, AndroidTV). Thanks a lot for your quick corrections!
