### ISSUE TITLE
New problem with access via TV guide

### ISSUE THREAD

**Issue by ldebt** [add-ons/plugin.video.vrt.nu#977]
Start KODI >open addon VRT NU > select TV guide > select Date > select channel > select program
>>> "Playback failed. One or more items failed to play. Check the log for more information about this message. OK" > Push OK >>>Back to program list and program fails to start.
Some programs actually do start wit TV guide. Using the option "VRT NU search" works always well.
Failure first detected 09.05.22 - 20h00.

**Comment by mediaminister** [comment]
Fixed in https://github.com/add-ons/plugin.video.vrt.nu/pull/986
