### ISSUE TITLE
2.5.11 stops live stream after a few seconds.

### ISSUE THREAD

**Issue by on4bam** [add-ons/plugin.video.vrt.nu#985]
### Describe the bug ###

Seems that after the update to 2.5.11 live streams stop working after a few seconds.

1. Go to Live kijken
2. Click on Stu Bru Live
After a few seconds the video freezes, a bit later sound stops too. Add-on is not frozen and reacts to "stop" and "exit".

Other instance:
1. Go to Live kijken
2. Click on Stu Bru Live
After a few seconds LibreElec reboots and takes longer than normal to completely start.

Other instance:
1. Go to Live kijken
2. Click on Een
After a short while (longer than for StuBru) video freezes, sound continues until it's stopped on the remote control.

- Operating system:
- Kodi version: 19.4 (LibreElec 10.0.2
- Addon version:2.5.11
- Using a VPN: yes/no No
- Country you are using the addon from: 

### Log (if available) ###
```paste below


```

**Comment by mediaminister** [comment]
Strange, nothing has changed to the LiveTV menu and live streaming in version v2.5.11
Maybe something else is causing this problem.
Did you install a new LibreELEC or Widevine CDM version?

**Comment by on4bam** [comment]
Started the Rpi this evening and had it play StuBru live for over an hour without a problem. So weird yesterday the same actions had the same result (stall or reboot) and today all is well again.

**Comment by on4bam** [comment]
No more problems running VRTnu add-on a few hours yesterday evening. Live as well as from the favorites list.
Still wondering what happened on Monday after the update to 2.5.11 as I could reproduce  several times even after cold/hot reboots of the RPi
In any case.. solved.
