### ISSUE TITLE
Empty program in plug-in <-> actual content in official app

### ISSUE THREAD

**Issue by stefaanderoeck** [add-ons/plugin.video.vrt.nu#994]
### Describe the bug ###

"De smurfen" shows no episodes. I have tried selecting numerous other programs, but all that I've tried _do_ show episodes (such as "De spierketiers", but also the related but different program "De Smurfen - uit de oude doos")

### To Reproduce ###
1. Go to "Categorieën" - "Kinderen en jongeren" - "De smurfen"
2. Observe that no content is shown

### Expected behavior ###

Expected to see the content shown in the official VRT.nu app:
1. Go to "Programma's" - and the same ("Categorieën"...) as above
2. Observe that "26 of 52 episodes" are displayed

### Additional context ###

- Operating system: LibreElec RPi4.arm-10.0.2
- Kodi version: Kodi Matrix v19.4
- Addon version: v2.5.12+matrix.1
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
no relevant mention found in logs, will increase log level or sth on request if relevant

**Comment by mediaminister** [comment]
I fixed it.
Please test
Test package for Kodi 19 Matrix[plugin.video.vrt.nu-2.5.12+matrix.1-smurfs-accb5d8.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8794073/plugin.video.vrt.nu-2.5.12%2Bmatrix.1-smurfs-accb5d8.zip)
Test package for Kodi 18 Leia[plugin.video.vrt.nu-2.5.12-smurfs-accb5d8.zip](https://github.com/add-ons/plugin.video.vrt.nu/files/8794074/plugin.video.vrt.nu-2.5.12-smurfs-accb5d8.zip)

**Comment by stefaanderoeck** [comment]
Just tested it. Works like a charm!!
Many thanks. 
And so awesomely fast, you rock!! :smile:
