### ISSUE TITLE
Next Up integration not working anymore

### ISSUE THREAD

**Issue by vermope** [add-ons/plugin.video.vrt.nu#998]
Next Up integration stopped working. The Next Up window appears with the correct next episode, once it starts VRT Nu addon throws an error:
 FATAL <general>: [plugin.video.vrt.nu] Play Up Next with episodeId 1606322600025 failed

**Comment by mediaminister** [comment]
Should be fixed in the new release:
https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.19

**Comment by vermope** [comment]
Works perfect! Thanks.
